// Code generated by mockery v2.53.5. DO NOT EDIT.

// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	auth "agrinovagraphql/server/internal/graphql/domain/auth"
	context "context"

	master "agrinovagraphql/server/internal/graphql/domain/master"

	mock "github.com/stretchr/testify/mock"

	models "agrinovagraphql/server/internal/master/models"
)

// MockMasterService is an autogenerated mock type for the MasterService type
type MockMasterService struct {
	mock.Mock
}

type MockMasterService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMasterService) EXPECT() *MockMasterService_Expecter {
	return &MockMasterService_Expecter{mock: &_m.Mock}
}

// AssignUserToCompany provides a mock function with given fields: ctx, req, assignerID
func (_m *MockMasterService) AssignUserToCompany(ctx context.Context, req *models.AssignUserToCompanyRequest, assignerID string) (*auth.UserCompanyAssignment, error) {
	ret := _m.Called(ctx, req, assignerID)

	if len(ret) == 0 {
		panic("no return value specified for AssignUserToCompany")
	}

	var r0 *auth.UserCompanyAssignment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.AssignUserToCompanyRequest, string) (*auth.UserCompanyAssignment, error)); ok {
		return rf(ctx, req, assignerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.AssignUserToCompanyRequest, string) *auth.UserCompanyAssignment); ok {
		r0 = rf(ctx, req, assignerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.UserCompanyAssignment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.AssignUserToCompanyRequest, string) error); ok {
		r1 = rf(ctx, req, assignerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMasterService_AssignUserToCompany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignUserToCompany'
type MockMasterService_AssignUserToCompany_Call struct {
	*mock.Call
}

// AssignUserToCompany is a helper method to define mock.On call
//   - ctx context.Context
//   - req *models.AssignUserToCompanyRequest
//   - assignerID string
func (_e *MockMasterService_Expecter) AssignUserToCompany(ctx interface{}, req interface{}, assignerID interface{}) *MockMasterService_AssignUserToCompany_Call {
	return &MockMasterService_AssignUserToCompany_Call{Call: _e.mock.On("AssignUserToCompany", ctx, req, assignerID)}
}

func (_c *MockMasterService_AssignUserToCompany_Call) Run(run func(ctx context.Context, req *models.AssignUserToCompanyRequest, assignerID string)) *MockMasterService_AssignUserToCompany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.AssignUserToCompanyRequest), args[2].(string))
	})
	return _c
}

func (_c *MockMasterService_AssignUserToCompany_Call) Return(_a0 *auth.UserCompanyAssignment, _a1 error) *MockMasterService_AssignUserToCompany_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMasterService_AssignUserToCompany_Call) RunAndReturn(run func(context.Context, *models.AssignUserToCompanyRequest, string) (*auth.UserCompanyAssignment, error)) *MockMasterService_AssignUserToCompany_Call {
	_c.Call.Return(run)
	return _c
}

// AssignUserToDivision provides a mock function with given fields: ctx, req, assignerID
func (_m *MockMasterService) AssignUserToDivision(ctx context.Context, req *models.AssignUserToDivisionRequest, assignerID string) (*models.UserDivisionAssignment, error) {
	ret := _m.Called(ctx, req, assignerID)

	if len(ret) == 0 {
		panic("no return value specified for AssignUserToDivision")
	}

	var r0 *models.UserDivisionAssignment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.AssignUserToDivisionRequest, string) (*models.UserDivisionAssignment, error)); ok {
		return rf(ctx, req, assignerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.AssignUserToDivisionRequest, string) *models.UserDivisionAssignment); ok {
		r0 = rf(ctx, req, assignerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserDivisionAssignment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.AssignUserToDivisionRequest, string) error); ok {
		r1 = rf(ctx, req, assignerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMasterService_AssignUserToDivision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignUserToDivision'
type MockMasterService_AssignUserToDivision_Call struct {
	*mock.Call
}

// AssignUserToDivision is a helper method to define mock.On call
//   - ctx context.Context
//   - req *models.AssignUserToDivisionRequest
//   - assignerID string
func (_e *MockMasterService_Expecter) AssignUserToDivision(ctx interface{}, req interface{}, assignerID interface{}) *MockMasterService_AssignUserToDivision_Call {
	return &MockMasterService_AssignUserToDivision_Call{Call: _e.mock.On("AssignUserToDivision", ctx, req, assignerID)}
}

func (_c *MockMasterService_AssignUserToDivision_Call) Run(run func(ctx context.Context, req *models.AssignUserToDivisionRequest, assignerID string)) *MockMasterService_AssignUserToDivision_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.AssignUserToDivisionRequest), args[2].(string))
	})
	return _c
}

func (_c *MockMasterService_AssignUserToDivision_Call) Return(_a0 *models.UserDivisionAssignment, _a1 error) *MockMasterService_AssignUserToDivision_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMasterService_AssignUserToDivision_Call) RunAndReturn(run func(context.Context, *models.AssignUserToDivisionRequest, string) (*models.UserDivisionAssignment, error)) *MockMasterService_AssignUserToDivision_Call {
	_c.Call.Return(run)
	return _c
}

// AssignUserToEstate provides a mock function with given fields: ctx, req, assignerID
func (_m *MockMasterService) AssignUserToEstate(ctx context.Context, req *models.AssignUserToEstateRequest, assignerID string) (*models.UserEstateAssignment, error) {
	ret := _m.Called(ctx, req, assignerID)

	if len(ret) == 0 {
		panic("no return value specified for AssignUserToEstate")
	}

	var r0 *models.UserEstateAssignment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.AssignUserToEstateRequest, string) (*models.UserEstateAssignment, error)); ok {
		return rf(ctx, req, assignerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.AssignUserToEstateRequest, string) *models.UserEstateAssignment); ok {
		r0 = rf(ctx, req, assignerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserEstateAssignment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.AssignUserToEstateRequest, string) error); ok {
		r1 = rf(ctx, req, assignerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMasterService_AssignUserToEstate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignUserToEstate'
type MockMasterService_AssignUserToEstate_Call struct {
	*mock.Call
}

// AssignUserToEstate is a helper method to define mock.On call
//   - ctx context.Context
//   - req *models.AssignUserToEstateRequest
//   - assignerID string
func (_e *MockMasterService_Expecter) AssignUserToEstate(ctx interface{}, req interface{}, assignerID interface{}) *MockMasterService_AssignUserToEstate_Call {
	return &MockMasterService_AssignUserToEstate_Call{Call: _e.mock.On("AssignUserToEstate", ctx, req, assignerID)}
}

func (_c *MockMasterService_AssignUserToEstate_Call) Run(run func(ctx context.Context, req *models.AssignUserToEstateRequest, assignerID string)) *MockMasterService_AssignUserToEstate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.AssignUserToEstateRequest), args[2].(string))
	})
	return _c
}

func (_c *MockMasterService_AssignUserToEstate_Call) Return(_a0 *models.UserEstateAssignment, _a1 error) *MockMasterService_AssignUserToEstate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMasterService_AssignUserToEstate_Call) RunAndReturn(run func(context.Context, *models.AssignUserToEstateRequest, string) (*models.UserEstateAssignment, error)) *MockMasterService_AssignUserToEstate_Call {
	_c.Call.Return(run)
	return _c
}

// CountCompanies provides a mock function with given fields: ctx, filters, userID
func (_m *MockMasterService) CountCompanies(ctx context.Context, filters *models.MasterFilters, userID string) (int64, error) {
	ret := _m.Called(ctx, filters, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountCompanies")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.MasterFilters, string) (int64, error)); ok {
		return rf(ctx, filters, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.MasterFilters, string) int64); ok {
		r0 = rf(ctx, filters, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.MasterFilters, string) error); ok {
		r1 = rf(ctx, filters, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMasterService_CountCompanies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountCompanies'
type MockMasterService_CountCompanies_Call struct {
	*mock.Call
}

// CountCompanies is a helper method to define mock.On call
//   - ctx context.Context
//   - filters *models.MasterFilters
//   - userID string
func (_e *MockMasterService_Expecter) CountCompanies(ctx interface{}, filters interface{}, userID interface{}) *MockMasterService_CountCompanies_Call {
	return &MockMasterService_CountCompanies_Call{Call: _e.mock.On("CountCompanies", ctx, filters, userID)}
}

func (_c *MockMasterService_CountCompanies_Call) Run(run func(ctx context.Context, filters *models.MasterFilters, userID string)) *MockMasterService_CountCompanies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.MasterFilters), args[2].(string))
	})
	return _c
}

func (_c *MockMasterService_CountCompanies_Call) Return(_a0 int64, _a1 error) *MockMasterService_CountCompanies_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMasterService_CountCompanies_Call) RunAndReturn(run func(context.Context, *models.MasterFilters, string) (int64, error)) *MockMasterService_CountCompanies_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBlock provides a mock function with given fields: ctx, req, creatorID
func (_m *MockMasterService) CreateBlock(ctx context.Context, req *models.CreateBlockRequest, creatorID string) (*master.Block, error) {
	ret := _m.Called(ctx, req, creatorID)

	if len(ret) == 0 {
		panic("no return value specified for CreateBlock")
	}

	var r0 *master.Block
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.CreateBlockRequest, string) (*master.Block, error)); ok {
		return rf(ctx, req, creatorID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.CreateBlockRequest, string) *master.Block); ok {
		r0 = rf(ctx, req, creatorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*master.Block)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.CreateBlockRequest, string) error); ok {
		r1 = rf(ctx, req, creatorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMasterService_CreateBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBlock'
type MockMasterService_CreateBlock_Call struct {
	*mock.Call
}

// CreateBlock is a helper method to define mock.On call
//   - ctx context.Context
//   - req *models.CreateBlockRequest
//   - creatorID string
func (_e *MockMasterService_Expecter) CreateBlock(ctx interface{}, req interface{}, creatorID interface{}) *MockMasterService_CreateBlock_Call {
	return &MockMasterService_CreateBlock_Call{Call: _e.mock.On("CreateBlock", ctx, req, creatorID)}
}

func (_c *MockMasterService_CreateBlock_Call) Run(run func(ctx context.Context, req *models.CreateBlockRequest, creatorID string)) *MockMasterService_CreateBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.CreateBlockRequest), args[2].(string))
	})
	return _c
}

func (_c *MockMasterService_CreateBlock_Call) Return(_a0 *master.Block, _a1 error) *MockMasterService_CreateBlock_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMasterService_CreateBlock_Call) RunAndReturn(run func(context.Context, *models.CreateBlockRequest, string) (*master.Block, error)) *MockMasterService_CreateBlock_Call {
	_c.Call.Return(run)
	return _c
}

// CreateCompany provides a mock function with given fields: ctx, req, creatorID
func (_m *MockMasterService) CreateCompany(ctx context.Context, req *models.CreateCompanyRequest, creatorID string) (*master.Company, error) {
	ret := _m.Called(ctx, req, creatorID)

	if len(ret) == 0 {
		panic("no return value specified for CreateCompany")
	}

	var r0 *master.Company
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.CreateCompanyRequest, string) (*master.Company, error)); ok {
		return rf(ctx, req, creatorID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.CreateCompanyRequest, string) *master.Company); ok {
		r0 = rf(ctx, req, creatorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*master.Company)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.CreateCompanyRequest, string) error); ok {
		r1 = rf(ctx, req, creatorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMasterService_CreateCompany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCompany'
type MockMasterService_CreateCompany_Call struct {
	*mock.Call
}

// CreateCompany is a helper method to define mock.On call
//   - ctx context.Context
//   - req *models.CreateCompanyRequest
//   - creatorID string
func (_e *MockMasterService_Expecter) CreateCompany(ctx interface{}, req interface{}, creatorID interface{}) *MockMasterService_CreateCompany_Call {
	return &MockMasterService_CreateCompany_Call{Call: _e.mock.On("CreateCompany", ctx, req, creatorID)}
}

func (_c *MockMasterService_CreateCompany_Call) Run(run func(ctx context.Context, req *models.CreateCompanyRequest, creatorID string)) *MockMasterService_CreateCompany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.CreateCompanyRequest), args[2].(string))
	})
	return _c
}

func (_c *MockMasterService_CreateCompany_Call) Return(_a0 *master.Company, _a1 error) *MockMasterService_CreateCompany_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMasterService_CreateCompany_Call) RunAndReturn(run func(context.Context, *models.CreateCompanyRequest, string) (*master.Company, error)) *MockMasterService_CreateCompany_Call {
	_c.Call.Return(run)
	return _c
}

// CreateDivision provides a mock function with given fields: ctx, req, creatorID
func (_m *MockMasterService) CreateDivision(ctx context.Context, req *models.CreateDivisionRequest, creatorID string) (*master.Division, error) {
	ret := _m.Called(ctx, req, creatorID)

	if len(ret) == 0 {
		panic("no return value specified for CreateDivision")
	}

	var r0 *master.Division
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.CreateDivisionRequest, string) (*master.Division, error)); ok {
		return rf(ctx, req, creatorID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.CreateDivisionRequest, string) *master.Division); ok {
		r0 = rf(ctx, req, creatorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*master.Division)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.CreateDivisionRequest, string) error); ok {
		r1 = rf(ctx, req, creatorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMasterService_CreateDivision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDivision'
type MockMasterService_CreateDivision_Call struct {
	*mock.Call
}

// CreateDivision is a helper method to define mock.On call
//   - ctx context.Context
//   - req *models.CreateDivisionRequest
//   - creatorID string
func (_e *MockMasterService_Expecter) CreateDivision(ctx interface{}, req interface{}, creatorID interface{}) *MockMasterService_CreateDivision_Call {
	return &MockMasterService_CreateDivision_Call{Call: _e.mock.On("CreateDivision", ctx, req, creatorID)}
}

func (_c *MockMasterService_CreateDivision_Call) Run(run func(ctx context.Context, req *models.CreateDivisionRequest, creatorID string)) *MockMasterService_CreateDivision_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.CreateDivisionRequest), args[2].(string))
	})
	return _c
}

func (_c *MockMasterService_CreateDivision_Call) Return(_a0 *master.Division, _a1 error) *MockMasterService_CreateDivision_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMasterService_CreateDivision_Call) RunAndReturn(run func(context.Context, *models.CreateDivisionRequest, string) (*master.Division, error)) *MockMasterService_CreateDivision_Call {
	_c.Call.Return(run)
	return _c
}

// CreateEstate provides a mock function with given fields: ctx, req, creatorID
func (_m *MockMasterService) CreateEstate(ctx context.Context, req *models.CreateEstateRequest, creatorID string) (*master.Estate, error) {
	ret := _m.Called(ctx, req, creatorID)

	if len(ret) == 0 {
		panic("no return value specified for CreateEstate")
	}

	var r0 *master.Estate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.CreateEstateRequest, string) (*master.Estate, error)); ok {
		return rf(ctx, req, creatorID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.CreateEstateRequest, string) *master.Estate); ok {
		r0 = rf(ctx, req, creatorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*master.Estate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.CreateEstateRequest, string) error); ok {
		r1 = rf(ctx, req, creatorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMasterService_CreateEstate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEstate'
type MockMasterService_CreateEstate_Call struct {
	*mock.Call
}

// CreateEstate is a helper method to define mock.On call
//   - ctx context.Context
//   - req *models.CreateEstateRequest
//   - creatorID string
func (_e *MockMasterService_Expecter) CreateEstate(ctx interface{}, req interface{}, creatorID interface{}) *MockMasterService_CreateEstate_Call {
	return &MockMasterService_CreateEstate_Call{Call: _e.mock.On("CreateEstate", ctx, req, creatorID)}
}

func (_c *MockMasterService_CreateEstate_Call) Run(run func(ctx context.Context, req *models.CreateEstateRequest, creatorID string)) *MockMasterService_CreateEstate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.CreateEstateRequest), args[2].(string))
	})
	return _c
}

func (_c *MockMasterService_CreateEstate_Call) Return(_a0 *master.Estate, _a1 error) *MockMasterService_CreateEstate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMasterService_CreateEstate_Call) RunAndReturn(run func(context.Context, *models.CreateEstateRequest, string) (*master.Estate, error)) *MockMasterService_CreateEstate_Call {
	_c.Call.Return(run)
	return _c
}

// CreateLandType provides a mock function with given fields: ctx, req, creatorID
func (_m *MockMasterService) CreateLandType(ctx context.Context, req *models.CreateLandTypeRequest, creatorID string) (*master.LandType, error) {
	ret := _m.Called(ctx, req, creatorID)

	if len(ret) == 0 {
		panic("no return value specified for CreateLandType")
	}

	var r0 *master.LandType
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.CreateLandTypeRequest, string) (*master.LandType, error)); ok {
		return rf(ctx, req, creatorID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.CreateLandTypeRequest, string) *master.LandType); ok {
		r0 = rf(ctx, req, creatorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*master.LandType)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.CreateLandTypeRequest, string) error); ok {
		r1 = rf(ctx, req, creatorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMasterService_CreateLandType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateLandType'
type MockMasterService_CreateLandType_Call struct {
	*mock.Call
}

// CreateLandType is a helper method to define mock.On call
//   - ctx context.Context
//   - req *models.CreateLandTypeRequest
//   - creatorID string
func (_e *MockMasterService_Expecter) CreateLandType(ctx interface{}, req interface{}, creatorID interface{}) *MockMasterService_CreateLandType_Call {
	return &MockMasterService_CreateLandType_Call{Call: _e.mock.On("CreateLandType", ctx, req, creatorID)}
}

func (_c *MockMasterService_CreateLandType_Call) Run(run func(ctx context.Context, req *models.CreateLandTypeRequest, creatorID string)) *MockMasterService_CreateLandType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.CreateLandTypeRequest), args[2].(string))
	})
	return _c
}

func (_c *MockMasterService_CreateLandType_Call) Return(_a0 *master.LandType, _a1 error) *MockMasterService_CreateLandType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMasterService_CreateLandType_Call) RunAndReturn(run func(context.Context, *models.CreateLandTypeRequest, string) (*master.LandType, error)) *MockMasterService_CreateLandType_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTarifBlok provides a mock function with given fields: ctx, req, creatorID
func (_m *MockMasterService) CreateTarifBlok(ctx context.Context, req *models.CreateTarifBlokRequest, creatorID string) (*master.TarifBlok, error) {
	ret := _m.Called(ctx, req, creatorID)

	if len(ret) == 0 {
		panic("no return value specified for CreateTarifBlok")
	}

	var r0 *master.TarifBlok
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.CreateTarifBlokRequest, string) (*master.TarifBlok, error)); ok {
		return rf(ctx, req, creatorID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.CreateTarifBlokRequest, string) *master.TarifBlok); ok {
		r0 = rf(ctx, req, creatorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*master.TarifBlok)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.CreateTarifBlokRequest, string) error); ok {
		r1 = rf(ctx, req, creatorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMasterService_CreateTarifBlok_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTarifBlok'
type MockMasterService_CreateTarifBlok_Call struct {
	*mock.Call
}

// CreateTarifBlok is a helper method to define mock.On call
//   - ctx context.Context
//   - req *models.CreateTarifBlokRequest
//   - creatorID string
func (_e *MockMasterService_Expecter) CreateTarifBlok(ctx interface{}, req interface{}, creatorID interface{}) *MockMasterService_CreateTarifBlok_Call {
	return &MockMasterService_CreateTarifBlok_Call{Call: _e.mock.On("CreateTarifBlok", ctx, req, creatorID)}
}

func (_c *MockMasterService_CreateTarifBlok_Call) Run(run func(ctx context.Context, req *models.CreateTarifBlokRequest, creatorID string)) *MockMasterService_CreateTarifBlok_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.CreateTarifBlokRequest), args[2].(string))
	})
	return _c
}

func (_c *MockMasterService_CreateTarifBlok_Call) Return(_a0 *master.TarifBlok, _a1 error) *MockMasterService_CreateTarifBlok_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMasterService_CreateTarifBlok_Call) RunAndReturn(run func(context.Context, *models.CreateTarifBlokRequest, string) (*master.TarifBlok, error)) *MockMasterService_CreateTarifBlok_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBlock provides a mock function with given fields: ctx, id, deleterID
func (_m *MockMasterService) DeleteBlock(ctx context.Context, id string, deleterID string) error {
	ret := _m.Called(ctx, id, deleterID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBlock")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, deleterID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMasterService_DeleteBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBlock'
type MockMasterService_DeleteBlock_Call struct {
	*mock.Call
}

// DeleteBlock is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - deleterID string
func (_e *MockMasterService_Expecter) DeleteBlock(ctx interface{}, id interface{}, deleterID interface{}) *MockMasterService_DeleteBlock_Call {
	return &MockMasterService_DeleteBlock_Call{Call: _e.mock.On("DeleteBlock", ctx, id, deleterID)}
}

func (_c *MockMasterService_DeleteBlock_Call) Run(run func(ctx context.Context, id string, deleterID string)) *MockMasterService_DeleteBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockMasterService_DeleteBlock_Call) Return(_a0 error) *MockMasterService_DeleteBlock_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMasterService_DeleteBlock_Call) RunAndReturn(run func(context.Context, string, string) error) *MockMasterService_DeleteBlock_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCompany provides a mock function with given fields: ctx, id, deleterID
func (_m *MockMasterService) DeleteCompany(ctx context.Context, id string, deleterID string) error {
	ret := _m.Called(ctx, id, deleterID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCompany")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, deleterID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMasterService_DeleteCompany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCompany'
type MockMasterService_DeleteCompany_Call struct {
	*mock.Call
}

// DeleteCompany is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - deleterID string
func (_e *MockMasterService_Expecter) DeleteCompany(ctx interface{}, id interface{}, deleterID interface{}) *MockMasterService_DeleteCompany_Call {
	return &MockMasterService_DeleteCompany_Call{Call: _e.mock.On("DeleteCompany", ctx, id, deleterID)}
}

func (_c *MockMasterService_DeleteCompany_Call) Run(run func(ctx context.Context, id string, deleterID string)) *MockMasterService_DeleteCompany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockMasterService_DeleteCompany_Call) Return(_a0 error) *MockMasterService_DeleteCompany_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMasterService_DeleteCompany_Call) RunAndReturn(run func(context.Context, string, string) error) *MockMasterService_DeleteCompany_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteDivision provides a mock function with given fields: ctx, id, deleterID
func (_m *MockMasterService) DeleteDivision(ctx context.Context, id string, deleterID string) error {
	ret := _m.Called(ctx, id, deleterID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDivision")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, deleterID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMasterService_DeleteDivision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDivision'
type MockMasterService_DeleteDivision_Call struct {
	*mock.Call
}

// DeleteDivision is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - deleterID string
func (_e *MockMasterService_Expecter) DeleteDivision(ctx interface{}, id interface{}, deleterID interface{}) *MockMasterService_DeleteDivision_Call {
	return &MockMasterService_DeleteDivision_Call{Call: _e.mock.On("DeleteDivision", ctx, id, deleterID)}
}

func (_c *MockMasterService_DeleteDivision_Call) Run(run func(ctx context.Context, id string, deleterID string)) *MockMasterService_DeleteDivision_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockMasterService_DeleteDivision_Call) Return(_a0 error) *MockMasterService_DeleteDivision_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMasterService_DeleteDivision_Call) RunAndReturn(run func(context.Context, string, string) error) *MockMasterService_DeleteDivision_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteEstate provides a mock function with given fields: ctx, id, deleterID
func (_m *MockMasterService) DeleteEstate(ctx context.Context, id string, deleterID string) error {
	ret := _m.Called(ctx, id, deleterID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEstate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, deleterID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMasterService_DeleteEstate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEstate'
type MockMasterService_DeleteEstate_Call struct {
	*mock.Call
}

// DeleteEstate is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - deleterID string
func (_e *MockMasterService_Expecter) DeleteEstate(ctx interface{}, id interface{}, deleterID interface{}) *MockMasterService_DeleteEstate_Call {
	return &MockMasterService_DeleteEstate_Call{Call: _e.mock.On("DeleteEstate", ctx, id, deleterID)}
}

func (_c *MockMasterService_DeleteEstate_Call) Run(run func(ctx context.Context, id string, deleterID string)) *MockMasterService_DeleteEstate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockMasterService_DeleteEstate_Call) Return(_a0 error) *MockMasterService_DeleteEstate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMasterService_DeleteEstate_Call) RunAndReturn(run func(context.Context, string, string) error) *MockMasterService_DeleteEstate_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteLandType provides a mock function with given fields: ctx, id, deleterID
func (_m *MockMasterService) DeleteLandType(ctx context.Context, id string, deleterID string) error {
	ret := _m.Called(ctx, id, deleterID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLandType")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, deleterID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMasterService_DeleteLandType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteLandType'
type MockMasterService_DeleteLandType_Call struct {
	*mock.Call
}

// DeleteLandType is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - deleterID string
func (_e *MockMasterService_Expecter) DeleteLandType(ctx interface{}, id interface{}, deleterID interface{}) *MockMasterService_DeleteLandType_Call {
	return &MockMasterService_DeleteLandType_Call{Call: _e.mock.On("DeleteLandType", ctx, id, deleterID)}
}

func (_c *MockMasterService_DeleteLandType_Call) Run(run func(ctx context.Context, id string, deleterID string)) *MockMasterService_DeleteLandType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockMasterService_DeleteLandType_Call) Return(_a0 error) *MockMasterService_DeleteLandType_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMasterService_DeleteLandType_Call) RunAndReturn(run func(context.Context, string, string) error) *MockMasterService_DeleteLandType_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTarifBlok provides a mock function with given fields: ctx, id, deleterID
func (_m *MockMasterService) DeleteTarifBlok(ctx context.Context, id string, deleterID string) error {
	ret := _m.Called(ctx, id, deleterID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTarifBlok")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, deleterID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMasterService_DeleteTarifBlok_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTarifBlok'
type MockMasterService_DeleteTarifBlok_Call struct {
	*mock.Call
}

// DeleteTarifBlok is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - deleterID string
func (_e *MockMasterService_Expecter) DeleteTarifBlok(ctx interface{}, id interface{}, deleterID interface{}) *MockMasterService_DeleteTarifBlok_Call {
	return &MockMasterService_DeleteTarifBlok_Call{Call: _e.mock.On("DeleteTarifBlok", ctx, id, deleterID)}
}

func (_c *MockMasterService_DeleteTarifBlok_Call) Run(run func(ctx context.Context, id string, deleterID string)) *MockMasterService_DeleteTarifBlok_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockMasterService_DeleteTarifBlok_Call) Return(_a0 error) *MockMasterService_DeleteTarifBlok_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMasterService_DeleteTarifBlok_Call) RunAndReturn(run func(context.Context, string, string) error) *MockMasterService_DeleteTarifBlok_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlockByID provides a mock function with given fields: ctx, id, userID
func (_m *MockMasterService) GetBlockByID(ctx context.Context, id string, userID string) (*master.Block, error) {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetBlockByID")
	}

	var r0 *master.Block
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*master.Block, error)); ok {
		return rf(ctx, id, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *master.Block); ok {
		r0 = rf(ctx, id, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*master.Block)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMasterService_GetBlockByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlockByID'
type MockMasterService_GetBlockByID_Call struct {
	*mock.Call
}

// GetBlockByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - userID string
func (_e *MockMasterService_Expecter) GetBlockByID(ctx interface{}, id interface{}, userID interface{}) *MockMasterService_GetBlockByID_Call {
	return &MockMasterService_GetBlockByID_Call{Call: _e.mock.On("GetBlockByID", ctx, id, userID)}
}

func (_c *MockMasterService_GetBlockByID_Call) Run(run func(ctx context.Context, id string, userID string)) *MockMasterService_GetBlockByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockMasterService_GetBlockByID_Call) Return(_a0 *master.Block, _a1 error) *MockMasterService_GetBlockByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMasterService_GetBlockByID_Call) RunAndReturn(run func(context.Context, string, string) (*master.Block, error)) *MockMasterService_GetBlockByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlocks provides a mock function with given fields: ctx, filters, userID
func (_m *MockMasterService) GetBlocks(ctx context.Context, filters *models.MasterFilters, userID string) ([]*master.Block, error) {
	ret := _m.Called(ctx, filters, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetBlocks")
	}

	var r0 []*master.Block
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.MasterFilters, string) ([]*master.Block, error)); ok {
		return rf(ctx, filters, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.MasterFilters, string) []*master.Block); ok {
		r0 = rf(ctx, filters, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*master.Block)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.MasterFilters, string) error); ok {
		r1 = rf(ctx, filters, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMasterService_GetBlocks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlocks'
type MockMasterService_GetBlocks_Call struct {
	*mock.Call
}

// GetBlocks is a helper method to define mock.On call
//   - ctx context.Context
//   - filters *models.MasterFilters
//   - userID string
func (_e *MockMasterService_Expecter) GetBlocks(ctx interface{}, filters interface{}, userID interface{}) *MockMasterService_GetBlocks_Call {
	return &MockMasterService_GetBlocks_Call{Call: _e.mock.On("GetBlocks", ctx, filters, userID)}
}

func (_c *MockMasterService_GetBlocks_Call) Run(run func(ctx context.Context, filters *models.MasterFilters, userID string)) *MockMasterService_GetBlocks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.MasterFilters), args[2].(string))
	})
	return _c
}

func (_c *MockMasterService_GetBlocks_Call) Return(_a0 []*master.Block, _a1 error) *MockMasterService_GetBlocks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMasterService_GetBlocks_Call) RunAndReturn(run func(context.Context, *models.MasterFilters, string) ([]*master.Block, error)) *MockMasterService_GetBlocks_Call {
	_c.Call.Return(run)
	return _c
}

// GetCompanies provides a mock function with given fields: ctx, filters, userID
func (_m *MockMasterService) GetCompanies(ctx context.Context, filters *models.MasterFilters, userID string) ([]*master.Company, error) {
	ret := _m.Called(ctx, filters, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetCompanies")
	}

	var r0 []*master.Company
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.MasterFilters, string) ([]*master.Company, error)); ok {
		return rf(ctx, filters, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.MasterFilters, string) []*master.Company); ok {
		r0 = rf(ctx, filters, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*master.Company)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.MasterFilters, string) error); ok {
		r1 = rf(ctx, filters, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMasterService_GetCompanies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCompanies'
type MockMasterService_GetCompanies_Call struct {
	*mock.Call
}

// GetCompanies is a helper method to define mock.On call
//   - ctx context.Context
//   - filters *models.MasterFilters
//   - userID string
func (_e *MockMasterService_Expecter) GetCompanies(ctx interface{}, filters interface{}, userID interface{}) *MockMasterService_GetCompanies_Call {
	return &MockMasterService_GetCompanies_Call{Call: _e.mock.On("GetCompanies", ctx, filters, userID)}
}

func (_c *MockMasterService_GetCompanies_Call) Run(run func(ctx context.Context, filters *models.MasterFilters, userID string)) *MockMasterService_GetCompanies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.MasterFilters), args[2].(string))
	})
	return _c
}

func (_c *MockMasterService_GetCompanies_Call) Return(_a0 []*master.Company, _a1 error) *MockMasterService_GetCompanies_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMasterService_GetCompanies_Call) RunAndReturn(run func(context.Context, *models.MasterFilters, string) ([]*master.Company, error)) *MockMasterService_GetCompanies_Call {
	_c.Call.Return(run)
	return _c
}

// GetCompanyAssignments provides a mock function with given fields: ctx, userID
func (_m *MockMasterService) GetCompanyAssignments(ctx context.Context, userID string) ([]*auth.UserCompanyAssignment, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetCompanyAssignments")
	}

	var r0 []*auth.UserCompanyAssignment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*auth.UserCompanyAssignment, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*auth.UserCompanyAssignment); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*auth.UserCompanyAssignment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMasterService_GetCompanyAssignments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCompanyAssignments'
type MockMasterService_GetCompanyAssignments_Call struct {
	*mock.Call
}

// GetCompanyAssignments is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockMasterService_Expecter) GetCompanyAssignments(ctx interface{}, userID interface{}) *MockMasterService_GetCompanyAssignments_Call {
	return &MockMasterService_GetCompanyAssignments_Call{Call: _e.mock.On("GetCompanyAssignments", ctx, userID)}
}

func (_c *MockMasterService_GetCompanyAssignments_Call) Run(run func(ctx context.Context, userID string)) *MockMasterService_GetCompanyAssignments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMasterService_GetCompanyAssignments_Call) Return(_a0 []*auth.UserCompanyAssignment, _a1 error) *MockMasterService_GetCompanyAssignments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMasterService_GetCompanyAssignments_Call) RunAndReturn(run func(context.Context, string) ([]*auth.UserCompanyAssignment, error)) *MockMasterService_GetCompanyAssignments_Call {
	_c.Call.Return(run)
	return _c
}

// GetCompanyByID provides a mock function with given fields: ctx, id, userID
func (_m *MockMasterService) GetCompanyByID(ctx context.Context, id string, userID string) (*master.Company, error) {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetCompanyByID")
	}

	var r0 *master.Company
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*master.Company, error)); ok {
		return rf(ctx, id, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *master.Company); ok {
		r0 = rf(ctx, id, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*master.Company)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMasterService_GetCompanyByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCompanyByID'
type MockMasterService_GetCompanyByID_Call struct {
	*mock.Call
}

// GetCompanyByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - userID string
func (_e *MockMasterService_Expecter) GetCompanyByID(ctx interface{}, id interface{}, userID interface{}) *MockMasterService_GetCompanyByID_Call {
	return &MockMasterService_GetCompanyByID_Call{Call: _e.mock.On("GetCompanyByID", ctx, id, userID)}
}

func (_c *MockMasterService_GetCompanyByID_Call) Run(run func(ctx context.Context, id string, userID string)) *MockMasterService_GetCompanyByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockMasterService_GetCompanyByID_Call) Return(_a0 *master.Company, _a1 error) *MockMasterService_GetCompanyByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMasterService_GetCompanyByID_Call) RunAndReturn(run func(context.Context, string, string) (*master.Company, error)) *MockMasterService_GetCompanyByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetDivisionAssignments provides a mock function with given fields: ctx, userID
func (_m *MockMasterService) GetDivisionAssignments(ctx context.Context, userID string) ([]*models.UserDivisionAssignment, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetDivisionAssignments")
	}

	var r0 []*models.UserDivisionAssignment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*models.UserDivisionAssignment, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*models.UserDivisionAssignment); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.UserDivisionAssignment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMasterService_GetDivisionAssignments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDivisionAssignments'
type MockMasterService_GetDivisionAssignments_Call struct {
	*mock.Call
}

// GetDivisionAssignments is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockMasterService_Expecter) GetDivisionAssignments(ctx interface{}, userID interface{}) *MockMasterService_GetDivisionAssignments_Call {
	return &MockMasterService_GetDivisionAssignments_Call{Call: _e.mock.On("GetDivisionAssignments", ctx, userID)}
}

func (_c *MockMasterService_GetDivisionAssignments_Call) Run(run func(ctx context.Context, userID string)) *MockMasterService_GetDivisionAssignments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMasterService_GetDivisionAssignments_Call) Return(_a0 []*models.UserDivisionAssignment, _a1 error) *MockMasterService_GetDivisionAssignments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMasterService_GetDivisionAssignments_Call) RunAndReturn(run func(context.Context, string) ([]*models.UserDivisionAssignment, error)) *MockMasterService_GetDivisionAssignments_Call {
	_c.Call.Return(run)
	return _c
}

// GetDivisionByID provides a mock function with given fields: ctx, id, userID
func (_m *MockMasterService) GetDivisionByID(ctx context.Context, id string, userID string) (*master.Division, error) {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetDivisionByID")
	}

	var r0 *master.Division
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*master.Division, error)); ok {
		return rf(ctx, id, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *master.Division); ok {
		r0 = rf(ctx, id, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*master.Division)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMasterService_GetDivisionByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDivisionByID'
type MockMasterService_GetDivisionByID_Call struct {
	*mock.Call
}

// GetDivisionByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - userID string
func (_e *MockMasterService_Expecter) GetDivisionByID(ctx interface{}, id interface{}, userID interface{}) *MockMasterService_GetDivisionByID_Call {
	return &MockMasterService_GetDivisionByID_Call{Call: _e.mock.On("GetDivisionByID", ctx, id, userID)}
}

func (_c *MockMasterService_GetDivisionByID_Call) Run(run func(ctx context.Context, id string, userID string)) *MockMasterService_GetDivisionByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockMasterService_GetDivisionByID_Call) Return(_a0 *master.Division, _a1 error) *MockMasterService_GetDivisionByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMasterService_GetDivisionByID_Call) RunAndReturn(run func(context.Context, string, string) (*master.Division, error)) *MockMasterService_GetDivisionByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetDivisions provides a mock function with given fields: ctx, filters, userID
func (_m *MockMasterService) GetDivisions(ctx context.Context, filters *models.MasterFilters, userID string) ([]*master.Division, error) {
	ret := _m.Called(ctx, filters, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetDivisions")
	}

	var r0 []*master.Division
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.MasterFilters, string) ([]*master.Division, error)); ok {
		return rf(ctx, filters, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.MasterFilters, string) []*master.Division); ok {
		r0 = rf(ctx, filters, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*master.Division)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.MasterFilters, string) error); ok {
		r1 = rf(ctx, filters, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMasterService_GetDivisions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDivisions'
type MockMasterService_GetDivisions_Call struct {
	*mock.Call
}

// GetDivisions is a helper method to define mock.On call
//   - ctx context.Context
//   - filters *models.MasterFilters
//   - userID string
func (_e *MockMasterService_Expecter) GetDivisions(ctx interface{}, filters interface{}, userID interface{}) *MockMasterService_GetDivisions_Call {
	return &MockMasterService_GetDivisions_Call{Call: _e.mock.On("GetDivisions", ctx, filters, userID)}
}

func (_c *MockMasterService_GetDivisions_Call) Run(run func(ctx context.Context, filters *models.MasterFilters, userID string)) *MockMasterService_GetDivisions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.MasterFilters), args[2].(string))
	})
	return _c
}

func (_c *MockMasterService_GetDivisions_Call) Return(_a0 []*master.Division, _a1 error) *MockMasterService_GetDivisions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMasterService_GetDivisions_Call) RunAndReturn(run func(context.Context, *models.MasterFilters, string) ([]*master.Division, error)) *MockMasterService_GetDivisions_Call {
	_c.Call.Return(run)
	return _c
}

// GetEstateAssignments provides a mock function with given fields: ctx, userID
func (_m *MockMasterService) GetEstateAssignments(ctx context.Context, userID string) ([]*models.UserEstateAssignment, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetEstateAssignments")
	}

	var r0 []*models.UserEstateAssignment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*models.UserEstateAssignment, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*models.UserEstateAssignment); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.UserEstateAssignment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMasterService_GetEstateAssignments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEstateAssignments'
type MockMasterService_GetEstateAssignments_Call struct {
	*mock.Call
}

// GetEstateAssignments is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockMasterService_Expecter) GetEstateAssignments(ctx interface{}, userID interface{}) *MockMasterService_GetEstateAssignments_Call {
	return &MockMasterService_GetEstateAssignments_Call{Call: _e.mock.On("GetEstateAssignments", ctx, userID)}
}

func (_c *MockMasterService_GetEstateAssignments_Call) Run(run func(ctx context.Context, userID string)) *MockMasterService_GetEstateAssignments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMasterService_GetEstateAssignments_Call) Return(_a0 []*models.UserEstateAssignment, _a1 error) *MockMasterService_GetEstateAssignments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMasterService_GetEstateAssignments_Call) RunAndReturn(run func(context.Context, string) ([]*models.UserEstateAssignment, error)) *MockMasterService_GetEstateAssignments_Call {
	_c.Call.Return(run)
	return _c
}

// GetEstateByID provides a mock function with given fields: ctx, id, userID
func (_m *MockMasterService) GetEstateByID(ctx context.Context, id string, userID string) (*master.Estate, error) {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetEstateByID")
	}

	var r0 *master.Estate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*master.Estate, error)); ok {
		return rf(ctx, id, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *master.Estate); ok {
		r0 = rf(ctx, id, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*master.Estate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMasterService_GetEstateByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEstateByID'
type MockMasterService_GetEstateByID_Call struct {
	*mock.Call
}

// GetEstateByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - userID string
func (_e *MockMasterService_Expecter) GetEstateByID(ctx interface{}, id interface{}, userID interface{}) *MockMasterService_GetEstateByID_Call {
	return &MockMasterService_GetEstateByID_Call{Call: _e.mock.On("GetEstateByID", ctx, id, userID)}
}

func (_c *MockMasterService_GetEstateByID_Call) Run(run func(ctx context.Context, id string, userID string)) *MockMasterService_GetEstateByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockMasterService_GetEstateByID_Call) Return(_a0 *master.Estate, _a1 error) *MockMasterService_GetEstateByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMasterService_GetEstateByID_Call) RunAndReturn(run func(context.Context, string, string) (*master.Estate, error)) *MockMasterService_GetEstateByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetEstates provides a mock function with given fields: ctx, filters, userID
func (_m *MockMasterService) GetEstates(ctx context.Context, filters *models.MasterFilters, userID string) ([]*master.Estate, error) {
	ret := _m.Called(ctx, filters, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetEstates")
	}

	var r0 []*master.Estate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.MasterFilters, string) ([]*master.Estate, error)); ok {
		return rf(ctx, filters, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.MasterFilters, string) []*master.Estate); ok {
		r0 = rf(ctx, filters, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*master.Estate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.MasterFilters, string) error); ok {
		r1 = rf(ctx, filters, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMasterService_GetEstates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEstates'
type MockMasterService_GetEstates_Call struct {
	*mock.Call
}

// GetEstates is a helper method to define mock.On call
//   - ctx context.Context
//   - filters *models.MasterFilters
//   - userID string
func (_e *MockMasterService_Expecter) GetEstates(ctx interface{}, filters interface{}, userID interface{}) *MockMasterService_GetEstates_Call {
	return &MockMasterService_GetEstates_Call{Call: _e.mock.On("GetEstates", ctx, filters, userID)}
}

func (_c *MockMasterService_GetEstates_Call) Run(run func(ctx context.Context, filters *models.MasterFilters, userID string)) *MockMasterService_GetEstates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.MasterFilters), args[2].(string))
	})
	return _c
}

func (_c *MockMasterService_GetEstates_Call) Return(_a0 []*master.Estate, _a1 error) *MockMasterService_GetEstates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMasterService_GetEstates_Call) RunAndReturn(run func(context.Context, *models.MasterFilters, string) ([]*master.Estate, error)) *MockMasterService_GetEstates_Call {
	_c.Call.Return(run)
	return _c
}

// GetLandTypes provides a mock function with given fields: ctx, userID
func (_m *MockMasterService) GetLandTypes(ctx context.Context, userID string) ([]*master.LandType, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetLandTypes")
	}

	var r0 []*master.LandType
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*master.LandType, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*master.LandType); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*master.LandType)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMasterService_GetLandTypes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLandTypes'
type MockMasterService_GetLandTypes_Call struct {
	*mock.Call
}

// GetLandTypes is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockMasterService_Expecter) GetLandTypes(ctx interface{}, userID interface{}) *MockMasterService_GetLandTypes_Call {
	return &MockMasterService_GetLandTypes_Call{Call: _e.mock.On("GetLandTypes", ctx, userID)}
}

func (_c *MockMasterService_GetLandTypes_Call) Run(run func(ctx context.Context, userID string)) *MockMasterService_GetLandTypes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMasterService_GetLandTypes_Call) Return(_a0 []*master.LandType, _a1 error) *MockMasterService_GetLandTypes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMasterService_GetLandTypes_Call) RunAndReturn(run func(context.Context, string) ([]*master.LandType, error)) *MockMasterService_GetLandTypes_Call {
	_c.Call.Return(run)
	return _c
}

// GetMasterDataStatistics provides a mock function with given fields: ctx, userID, companyID
func (_m *MockMasterService) GetMasterDataStatistics(ctx context.Context, userID string, companyID *string) (*models.MasterDataStatistics, error) {
	ret := _m.Called(ctx, userID, companyID)

	if len(ret) == 0 {
		panic("no return value specified for GetMasterDataStatistics")
	}

	var r0 *models.MasterDataStatistics
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *string) (*models.MasterDataStatistics, error)); ok {
		return rf(ctx, userID, companyID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *string) *models.MasterDataStatistics); ok {
		r0 = rf(ctx, userID, companyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.MasterDataStatistics)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *string) error); ok {
		r1 = rf(ctx, userID, companyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMasterService_GetMasterDataStatistics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMasterDataStatistics'
type MockMasterService_GetMasterDataStatistics_Call struct {
	*mock.Call
}

// GetMasterDataStatistics is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - companyID *string
func (_e *MockMasterService_Expecter) GetMasterDataStatistics(ctx interface{}, userID interface{}, companyID interface{}) *MockMasterService_GetMasterDataStatistics_Call {
	return &MockMasterService_GetMasterDataStatistics_Call{Call: _e.mock.On("GetMasterDataStatistics", ctx, userID, companyID)}
}

func (_c *MockMasterService_GetMasterDataStatistics_Call) Run(run func(ctx context.Context, userID string, companyID *string)) *MockMasterService_GetMasterDataStatistics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*string))
	})
	return _c
}

func (_c *MockMasterService_GetMasterDataStatistics_Call) Return(_a0 *models.MasterDataStatistics, _a1 error) *MockMasterService_GetMasterDataStatistics_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMasterService_GetMasterDataStatistics_Call) RunAndReturn(run func(context.Context, string, *string) (*models.MasterDataStatistics, error)) *MockMasterService_GetMasterDataStatistics_Call {
	_c.Call.Return(run)
	return _c
}

// GetTarifBloks provides a mock function with given fields: ctx, userID
func (_m *MockMasterService) GetTarifBloks(ctx context.Context, userID string) ([]*master.TarifBlok, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetTarifBloks")
	}

	var r0 []*master.TarifBlok
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*master.TarifBlok, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*master.TarifBlok); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*master.TarifBlok)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMasterService_GetTarifBloks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTarifBloks'
type MockMasterService_GetTarifBloks_Call struct {
	*mock.Call
}

// GetTarifBloks is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockMasterService_Expecter) GetTarifBloks(ctx interface{}, userID interface{}) *MockMasterService_GetTarifBloks_Call {
	return &MockMasterService_GetTarifBloks_Call{Call: _e.mock.On("GetTarifBloks", ctx, userID)}
}

func (_c *MockMasterService_GetTarifBloks_Call) Run(run func(ctx context.Context, userID string)) *MockMasterService_GetTarifBloks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMasterService_GetTarifBloks_Call) Return(_a0 []*master.TarifBlok, _a1 error) *MockMasterService_GetTarifBloks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMasterService_GetTarifBloks_Call) RunAndReturn(run func(context.Context, string) ([]*master.TarifBlok, error)) *MockMasterService_GetTarifBloks_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserAssignments provides a mock function with given fields: ctx, userID
func (_m *MockMasterService) GetUserAssignments(ctx context.Context, userID string) (*models.UserAssignmentsResponse, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserAssignments")
	}

	var r0 *models.UserAssignmentsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.UserAssignmentsResponse, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.UserAssignmentsResponse); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserAssignmentsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMasterService_GetUserAssignments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserAssignments'
type MockMasterService_GetUserAssignments_Call struct {
	*mock.Call
}

// GetUserAssignments is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockMasterService_Expecter) GetUserAssignments(ctx interface{}, userID interface{}) *MockMasterService_GetUserAssignments_Call {
	return &MockMasterService_GetUserAssignments_Call{Call: _e.mock.On("GetUserAssignments", ctx, userID)}
}

func (_c *MockMasterService_GetUserAssignments_Call) Run(run func(ctx context.Context, userID string)) *MockMasterService_GetUserAssignments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMasterService_GetUserAssignments_Call) Return(_a0 *models.UserAssignmentsResponse, _a1 error) *MockMasterService_GetUserAssignments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMasterService_GetUserAssignments_Call) RunAndReturn(run func(context.Context, string) (*models.UserAssignmentsResponse, error)) *MockMasterService_GetUserAssignments_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveCompanyAssignment provides a mock function with given fields: ctx, id, removerID
func (_m *MockMasterService) RemoveCompanyAssignment(ctx context.Context, id string, removerID string) error {
	ret := _m.Called(ctx, id, removerID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveCompanyAssignment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, removerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMasterService_RemoveCompanyAssignment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveCompanyAssignment'
type MockMasterService_RemoveCompanyAssignment_Call struct {
	*mock.Call
}

// RemoveCompanyAssignment is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - removerID string
func (_e *MockMasterService_Expecter) RemoveCompanyAssignment(ctx interface{}, id interface{}, removerID interface{}) *MockMasterService_RemoveCompanyAssignment_Call {
	return &MockMasterService_RemoveCompanyAssignment_Call{Call: _e.mock.On("RemoveCompanyAssignment", ctx, id, removerID)}
}

func (_c *MockMasterService_RemoveCompanyAssignment_Call) Run(run func(ctx context.Context, id string, removerID string)) *MockMasterService_RemoveCompanyAssignment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockMasterService_RemoveCompanyAssignment_Call) Return(_a0 error) *MockMasterService_RemoveCompanyAssignment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMasterService_RemoveCompanyAssignment_Call) RunAndReturn(run func(context.Context, string, string) error) *MockMasterService_RemoveCompanyAssignment_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveDivisionAssignment provides a mock function with given fields: ctx, id, removerID
func (_m *MockMasterService) RemoveDivisionAssignment(ctx context.Context, id string, removerID string) error {
	ret := _m.Called(ctx, id, removerID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveDivisionAssignment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, removerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMasterService_RemoveDivisionAssignment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveDivisionAssignment'
type MockMasterService_RemoveDivisionAssignment_Call struct {
	*mock.Call
}

// RemoveDivisionAssignment is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - removerID string
func (_e *MockMasterService_Expecter) RemoveDivisionAssignment(ctx interface{}, id interface{}, removerID interface{}) *MockMasterService_RemoveDivisionAssignment_Call {
	return &MockMasterService_RemoveDivisionAssignment_Call{Call: _e.mock.On("RemoveDivisionAssignment", ctx, id, removerID)}
}

func (_c *MockMasterService_RemoveDivisionAssignment_Call) Run(run func(ctx context.Context, id string, removerID string)) *MockMasterService_RemoveDivisionAssignment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockMasterService_RemoveDivisionAssignment_Call) Return(_a0 error) *MockMasterService_RemoveDivisionAssignment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMasterService_RemoveDivisionAssignment_Call) RunAndReturn(run func(context.Context, string, string) error) *MockMasterService_RemoveDivisionAssignment_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveEstateAssignment provides a mock function with given fields: ctx, id, removerID
func (_m *MockMasterService) RemoveEstateAssignment(ctx context.Context, id string, removerID string) error {
	ret := _m.Called(ctx, id, removerID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveEstateAssignment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, removerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMasterService_RemoveEstateAssignment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveEstateAssignment'
type MockMasterService_RemoveEstateAssignment_Call struct {
	*mock.Call
}

// RemoveEstateAssignment is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - removerID string
func (_e *MockMasterService_Expecter) RemoveEstateAssignment(ctx interface{}, id interface{}, removerID interface{}) *MockMasterService_RemoveEstateAssignment_Call {
	return &MockMasterService_RemoveEstateAssignment_Call{Call: _e.mock.On("RemoveEstateAssignment", ctx, id, removerID)}
}

func (_c *MockMasterService_RemoveEstateAssignment_Call) Run(run func(ctx context.Context, id string, removerID string)) *MockMasterService_RemoveEstateAssignment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockMasterService_RemoveEstateAssignment_Call) Return(_a0 error) *MockMasterService_RemoveEstateAssignment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMasterService_RemoveEstateAssignment_Call) RunAndReturn(run func(context.Context, string, string) error) *MockMasterService_RemoveEstateAssignment_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBlock provides a mock function with given fields: ctx, req, updaterID
func (_m *MockMasterService) UpdateBlock(ctx context.Context, req *models.UpdateBlockRequest, updaterID string) (*master.Block, error) {
	ret := _m.Called(ctx, req, updaterID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBlock")
	}

	var r0 *master.Block
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.UpdateBlockRequest, string) (*master.Block, error)); ok {
		return rf(ctx, req, updaterID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.UpdateBlockRequest, string) *master.Block); ok {
		r0 = rf(ctx, req, updaterID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*master.Block)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.UpdateBlockRequest, string) error); ok {
		r1 = rf(ctx, req, updaterID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMasterService_UpdateBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBlock'
type MockMasterService_UpdateBlock_Call struct {
	*mock.Call
}

// UpdateBlock is a helper method to define mock.On call
//   - ctx context.Context
//   - req *models.UpdateBlockRequest
//   - updaterID string
func (_e *MockMasterService_Expecter) UpdateBlock(ctx interface{}, req interface{}, updaterID interface{}) *MockMasterService_UpdateBlock_Call {
	return &MockMasterService_UpdateBlock_Call{Call: _e.mock.On("UpdateBlock", ctx, req, updaterID)}
}

func (_c *MockMasterService_UpdateBlock_Call) Run(run func(ctx context.Context, req *models.UpdateBlockRequest, updaterID string)) *MockMasterService_UpdateBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.UpdateBlockRequest), args[2].(string))
	})
	return _c
}

func (_c *MockMasterService_UpdateBlock_Call) Return(_a0 *master.Block, _a1 error) *MockMasterService_UpdateBlock_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMasterService_UpdateBlock_Call) RunAndReturn(run func(context.Context, *models.UpdateBlockRequest, string) (*master.Block, error)) *MockMasterService_UpdateBlock_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCompany provides a mock function with given fields: ctx, req, updaterID
func (_m *MockMasterService) UpdateCompany(ctx context.Context, req *models.UpdateCompanyRequest, updaterID string) (*master.Company, error) {
	ret := _m.Called(ctx, req, updaterID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCompany")
	}

	var r0 *master.Company
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.UpdateCompanyRequest, string) (*master.Company, error)); ok {
		return rf(ctx, req, updaterID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.UpdateCompanyRequest, string) *master.Company); ok {
		r0 = rf(ctx, req, updaterID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*master.Company)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.UpdateCompanyRequest, string) error); ok {
		r1 = rf(ctx, req, updaterID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMasterService_UpdateCompany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCompany'
type MockMasterService_UpdateCompany_Call struct {
	*mock.Call
}

// UpdateCompany is a helper method to define mock.On call
//   - ctx context.Context
//   - req *models.UpdateCompanyRequest
//   - updaterID string
func (_e *MockMasterService_Expecter) UpdateCompany(ctx interface{}, req interface{}, updaterID interface{}) *MockMasterService_UpdateCompany_Call {
	return &MockMasterService_UpdateCompany_Call{Call: _e.mock.On("UpdateCompany", ctx, req, updaterID)}
}

func (_c *MockMasterService_UpdateCompany_Call) Run(run func(ctx context.Context, req *models.UpdateCompanyRequest, updaterID string)) *MockMasterService_UpdateCompany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.UpdateCompanyRequest), args[2].(string))
	})
	return _c
}

func (_c *MockMasterService_UpdateCompany_Call) Return(_a0 *master.Company, _a1 error) *MockMasterService_UpdateCompany_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMasterService_UpdateCompany_Call) RunAndReturn(run func(context.Context, *models.UpdateCompanyRequest, string) (*master.Company, error)) *MockMasterService_UpdateCompany_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDivision provides a mock function with given fields: ctx, req, updaterID
func (_m *MockMasterService) UpdateDivision(ctx context.Context, req *models.UpdateDivisionRequest, updaterID string) (*master.Division, error) {
	ret := _m.Called(ctx, req, updaterID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDivision")
	}

	var r0 *master.Division
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.UpdateDivisionRequest, string) (*master.Division, error)); ok {
		return rf(ctx, req, updaterID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.UpdateDivisionRequest, string) *master.Division); ok {
		r0 = rf(ctx, req, updaterID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*master.Division)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.UpdateDivisionRequest, string) error); ok {
		r1 = rf(ctx, req, updaterID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMasterService_UpdateDivision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDivision'
type MockMasterService_UpdateDivision_Call struct {
	*mock.Call
}

// UpdateDivision is a helper method to define mock.On call
//   - ctx context.Context
//   - req *models.UpdateDivisionRequest
//   - updaterID string
func (_e *MockMasterService_Expecter) UpdateDivision(ctx interface{}, req interface{}, updaterID interface{}) *MockMasterService_UpdateDivision_Call {
	return &MockMasterService_UpdateDivision_Call{Call: _e.mock.On("UpdateDivision", ctx, req, updaterID)}
}

func (_c *MockMasterService_UpdateDivision_Call) Run(run func(ctx context.Context, req *models.UpdateDivisionRequest, updaterID string)) *MockMasterService_UpdateDivision_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.UpdateDivisionRequest), args[2].(string))
	})
	return _c
}

func (_c *MockMasterService_UpdateDivision_Call) Return(_a0 *master.Division, _a1 error) *MockMasterService_UpdateDivision_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMasterService_UpdateDivision_Call) RunAndReturn(run func(context.Context, *models.UpdateDivisionRequest, string) (*master.Division, error)) *MockMasterService_UpdateDivision_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateEstate provides a mock function with given fields: ctx, req, updaterID
func (_m *MockMasterService) UpdateEstate(ctx context.Context, req *models.UpdateEstateRequest, updaterID string) (*master.Estate, error) {
	ret := _m.Called(ctx, req, updaterID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEstate")
	}

	var r0 *master.Estate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.UpdateEstateRequest, string) (*master.Estate, error)); ok {
		return rf(ctx, req, updaterID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.UpdateEstateRequest, string) *master.Estate); ok {
		r0 = rf(ctx, req, updaterID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*master.Estate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.UpdateEstateRequest, string) error); ok {
		r1 = rf(ctx, req, updaterID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMasterService_UpdateEstate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateEstate'
type MockMasterService_UpdateEstate_Call struct {
	*mock.Call
}

// UpdateEstate is a helper method to define mock.On call
//   - ctx context.Context
//   - req *models.UpdateEstateRequest
//   - updaterID string
func (_e *MockMasterService_Expecter) UpdateEstate(ctx interface{}, req interface{}, updaterID interface{}) *MockMasterService_UpdateEstate_Call {
	return &MockMasterService_UpdateEstate_Call{Call: _e.mock.On("UpdateEstate", ctx, req, updaterID)}
}

func (_c *MockMasterService_UpdateEstate_Call) Run(run func(ctx context.Context, req *models.UpdateEstateRequest, updaterID string)) *MockMasterService_UpdateEstate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.UpdateEstateRequest), args[2].(string))
	})
	return _c
}

func (_c *MockMasterService_UpdateEstate_Call) Return(_a0 *master.Estate, _a1 error) *MockMasterService_UpdateEstate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMasterService_UpdateEstate_Call) RunAndReturn(run func(context.Context, *models.UpdateEstateRequest, string) (*master.Estate, error)) *MockMasterService_UpdateEstate_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLandType provides a mock function with given fields: ctx, req, updaterID
func (_m *MockMasterService) UpdateLandType(ctx context.Context, req *models.UpdateLandTypeRequest, updaterID string) (*master.LandType, error) {
	ret := _m.Called(ctx, req, updaterID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLandType")
	}

	var r0 *master.LandType
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.UpdateLandTypeRequest, string) (*master.LandType, error)); ok {
		return rf(ctx, req, updaterID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.UpdateLandTypeRequest, string) *master.LandType); ok {
		r0 = rf(ctx, req, updaterID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*master.LandType)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.UpdateLandTypeRequest, string) error); ok {
		r1 = rf(ctx, req, updaterID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMasterService_UpdateLandType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLandType'
type MockMasterService_UpdateLandType_Call struct {
	*mock.Call
}

// UpdateLandType is a helper method to define mock.On call
//   - ctx context.Context
//   - req *models.UpdateLandTypeRequest
//   - updaterID string
func (_e *MockMasterService_Expecter) UpdateLandType(ctx interface{}, req interface{}, updaterID interface{}) *MockMasterService_UpdateLandType_Call {
	return &MockMasterService_UpdateLandType_Call{Call: _e.mock.On("UpdateLandType", ctx, req, updaterID)}
}

func (_c *MockMasterService_UpdateLandType_Call) Run(run func(ctx context.Context, req *models.UpdateLandTypeRequest, updaterID string)) *MockMasterService_UpdateLandType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.UpdateLandTypeRequest), args[2].(string))
	})
	return _c
}

func (_c *MockMasterService_UpdateLandType_Call) Return(_a0 *master.LandType, _a1 error) *MockMasterService_UpdateLandType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMasterService_UpdateLandType_Call) RunAndReturn(run func(context.Context, *models.UpdateLandTypeRequest, string) (*master.LandType, error)) *MockMasterService_UpdateLandType_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTarifBlok provides a mock function with given fields: ctx, req, updaterID
func (_m *MockMasterService) UpdateTarifBlok(ctx context.Context, req *models.UpdateTarifBlokRequest, updaterID string) (*master.TarifBlok, error) {
	ret := _m.Called(ctx, req, updaterID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTarifBlok")
	}

	var r0 *master.TarifBlok
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.UpdateTarifBlokRequest, string) (*master.TarifBlok, error)); ok {
		return rf(ctx, req, updaterID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.UpdateTarifBlokRequest, string) *master.TarifBlok); ok {
		r0 = rf(ctx, req, updaterID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*master.TarifBlok)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.UpdateTarifBlokRequest, string) error); ok {
		r1 = rf(ctx, req, updaterID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMasterService_UpdateTarifBlok_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTarifBlok'
type MockMasterService_UpdateTarifBlok_Call struct {
	*mock.Call
}

// UpdateTarifBlok is a helper method to define mock.On call
//   - ctx context.Context
//   - req *models.UpdateTarifBlokRequest
//   - updaterID string
func (_e *MockMasterService_Expecter) UpdateTarifBlok(ctx interface{}, req interface{}, updaterID interface{}) *MockMasterService_UpdateTarifBlok_Call {
	return &MockMasterService_UpdateTarifBlok_Call{Call: _e.mock.On("UpdateTarifBlok", ctx, req, updaterID)}
}

func (_c *MockMasterService_UpdateTarifBlok_Call) Run(run func(ctx context.Context, req *models.UpdateTarifBlokRequest, updaterID string)) *MockMasterService_UpdateTarifBlok_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.UpdateTarifBlokRequest), args[2].(string))
	})
	return _c
}

func (_c *MockMasterService_UpdateTarifBlok_Call) Return(_a0 *master.TarifBlok, _a1 error) *MockMasterService_UpdateTarifBlok_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMasterService_UpdateTarifBlok_Call) RunAndReturn(run func(context.Context, *models.UpdateTarifBlokRequest, string) (*master.TarifBlok, error)) *MockMasterService_UpdateTarifBlok_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateCompanyAccess provides a mock function with given fields: ctx, userID, companyID
func (_m *MockMasterService) ValidateCompanyAccess(ctx context.Context, userID string, companyID string) error {
	ret := _m.Called(ctx, userID, companyID)

	if len(ret) == 0 {
		panic("no return value specified for ValidateCompanyAccess")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, companyID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMasterService_ValidateCompanyAccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateCompanyAccess'
type MockMasterService_ValidateCompanyAccess_Call struct {
	*mock.Call
}

// ValidateCompanyAccess is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - companyID string
func (_e *MockMasterService_Expecter) ValidateCompanyAccess(ctx interface{}, userID interface{}, companyID interface{}) *MockMasterService_ValidateCompanyAccess_Call {
	return &MockMasterService_ValidateCompanyAccess_Call{Call: _e.mock.On("ValidateCompanyAccess", ctx, userID, companyID)}
}

func (_c *MockMasterService_ValidateCompanyAccess_Call) Run(run func(ctx context.Context, userID string, companyID string)) *MockMasterService_ValidateCompanyAccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockMasterService_ValidateCompanyAccess_Call) Return(_a0 error) *MockMasterService_ValidateCompanyAccess_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMasterService_ValidateCompanyAccess_Call) RunAndReturn(run func(context.Context, string, string) error) *MockMasterService_ValidateCompanyAccess_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateDivisionAccess provides a mock function with given fields: ctx, userID, divisionID
func (_m *MockMasterService) ValidateDivisionAccess(ctx context.Context, userID string, divisionID string) error {
	ret := _m.Called(ctx, userID, divisionID)

	if len(ret) == 0 {
		panic("no return value specified for ValidateDivisionAccess")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, divisionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMasterService_ValidateDivisionAccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateDivisionAccess'
type MockMasterService_ValidateDivisionAccess_Call struct {
	*mock.Call
}

// ValidateDivisionAccess is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - divisionID string
func (_e *MockMasterService_Expecter) ValidateDivisionAccess(ctx interface{}, userID interface{}, divisionID interface{}) *MockMasterService_ValidateDivisionAccess_Call {
	return &MockMasterService_ValidateDivisionAccess_Call{Call: _e.mock.On("ValidateDivisionAccess", ctx, userID, divisionID)}
}

func (_c *MockMasterService_ValidateDivisionAccess_Call) Run(run func(ctx context.Context, userID string, divisionID string)) *MockMasterService_ValidateDivisionAccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockMasterService_ValidateDivisionAccess_Call) Return(_a0 error) *MockMasterService_ValidateDivisionAccess_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMasterService_ValidateDivisionAccess_Call) RunAndReturn(run func(context.Context, string, string) error) *MockMasterService_ValidateDivisionAccess_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateEstateAccess provides a mock function with given fields: ctx, userID, estateID
func (_m *MockMasterService) ValidateEstateAccess(ctx context.Context, userID string, estateID string) error {
	ret := _m.Called(ctx, userID, estateID)

	if len(ret) == 0 {
		panic("no return value specified for ValidateEstateAccess")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, estateID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMasterService_ValidateEstateAccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateEstateAccess'
type MockMasterService_ValidateEstateAccess_Call struct {
	*mock.Call
}

// ValidateEstateAccess is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - estateID string
func (_e *MockMasterService_Expecter) ValidateEstateAccess(ctx interface{}, userID interface{}, estateID interface{}) *MockMasterService_ValidateEstateAccess_Call {
	return &MockMasterService_ValidateEstateAccess_Call{Call: _e.mock.On("ValidateEstateAccess", ctx, userID, estateID)}
}

func (_c *MockMasterService_ValidateEstateAccess_Call) Run(run func(ctx context.Context, userID string, estateID string)) *MockMasterService_ValidateEstateAccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockMasterService_ValidateEstateAccess_Call) Return(_a0 error) *MockMasterService_ValidateEstateAccess_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMasterService_ValidateEstateAccess_Call) RunAndReturn(run func(context.Context, string, string) error) *MockMasterService_ValidateEstateAccess_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateUserRole provides a mock function with given fields: userRole, allowedRoles
func (_m *MockMasterService) ValidateUserRole(userRole auth.UserRole, allowedRoles []auth.UserRole) error {
	ret := _m.Called(userRole, allowedRoles)

	if len(ret) == 0 {
		panic("no return value specified for ValidateUserRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(auth.UserRole, []auth.UserRole) error); ok {
		r0 = rf(userRole, allowedRoles)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMasterService_ValidateUserRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateUserRole'
type MockMasterService_ValidateUserRole_Call struct {
	*mock.Call
}

// ValidateUserRole is a helper method to define mock.On call
//   - userRole auth.UserRole
//   - allowedRoles []auth.UserRole
func (_e *MockMasterService_Expecter) ValidateUserRole(userRole interface{}, allowedRoles interface{}) *MockMasterService_ValidateUserRole_Call {
	return &MockMasterService_ValidateUserRole_Call{Call: _e.mock.On("ValidateUserRole", userRole, allowedRoles)}
}

func (_c *MockMasterService_ValidateUserRole_Call) Run(run func(userRole auth.UserRole, allowedRoles []auth.UserRole)) *MockMasterService_ValidateUserRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(auth.UserRole), args[1].([]auth.UserRole))
	})
	return _c
}

func (_c *MockMasterService_ValidateUserRole_Call) Return(_a0 error) *MockMasterService_ValidateUserRole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMasterService_ValidateUserRole_Call) RunAndReturn(run func(auth.UserRole, []auth.UserRole) error) *MockMasterService_ValidateUserRole_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMasterService creates a new instance of MockMasterService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMasterService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMasterService {
	mock := &MockMasterService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
