package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"agrinovagraphql/server/internal/graphql/domain/bkm"
	"context"
)

// BkmPotongBuahReport is the resolver for the bkmPotongBuahReport field.
func (r *queryResolver) BkmPotongBuahReport(ctx context.Context, filter bkm.BkmPotongBuahFilter) (*bkm.BkmPotongBuahSummary, error) {
	return r.BkmReportService.GetPotongBuahReport(ctx, &filter)
}

// BkmPotongBuahFlat is the resolver for the bkmPotongBuahFlat field.
func (r *queryResolver) BkmPotongBuahFlat(ctx context.Context, filter bkm.BkmPotongBuahFilter, page int32, limit int32) (*bkm.BkmPotongBuahFlatResponse, error) {
	return r.BkmReportService.GetPotongBuahFlat(ctx, &filter, page, limit)
}

// BkmPotongBuahAnalytics is the resolver for the bkmPotongBuahAnalytics field.
func (r *queryResolver) BkmPotongBuahAnalytics(ctx context.Context, filter bkm.BkmPotongBuahFilter, topN *int32) (*bkm.BkmPotongBuahAnalytics, error) {
	resolvedTopN := int32(10)
	if topN != nil {
		resolvedTopN = *topN
	}
	return r.BkmReportService.GetPotongBuahAnalytics(ctx, &filter, resolvedTopN)
}
