package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"agrinovagraphql/server/internal/graphql/generated"
	"agrinovagraphql/server/internal/middleware"
	"context"
	"fmt"
)

// RegisterFCMToken is the resolver for the registerFCMToken field.
func (r *mutationResolver) RegisterFCMToken(ctx context.Context, input generated.RegisterFCMTokenInput) (bool, error) {
	userID := middleware.GetUserFromContext(ctx)
	if userID == "" {
		return false, fmt.Errorf("authentication required")
	}

	err := r.HierarchyService.RegisterDeviceToken(ctx, userID, input.Token, input.Platform, input.DeviceID)
	if err != nil {
		return false, err
	}

	return true, nil
}

// UnregisterFCMToken is the resolver for the unregisterFCMToken field.
func (r *mutationResolver) UnregisterFCMToken(ctx context.Context, token string) (bool, error) {
	err := r.HierarchyService.UnregisterDeviceToken(ctx, token)
	if err != nil {
		return false, err
	}

	return true, nil
}
