package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"agrinovagraphql/server/internal/graphql/domain/features"
)

// =============================================================================
// Query Resolvers
// =============================================================================

// ListFeatures is the resolver for the listFeatures field.
func (r *queryResolver) ListFeatures(ctx context.Context, filter *features.FeatureFilterInput, page *int32, limit *int32) (*features.FeaturesResponse, error) {
	return r.FeatureResolver.ListFeatures(ctx, filter, page, limit)
}

// GetFeature is the resolver for the getFeature field.
func (r *queryResolver) GetFeature(ctx context.Context, id string) (*features.Feature, error) {
	return r.FeatureResolver.GetFeature(ctx, id)
}

// GetFeatureByName is the resolver for the getFeatureByName field.
func (r *queryResolver) GetFeatureByName(ctx context.Context, name string) (*features.Feature, error) {
	return r.FeatureResolver.GetFeatureByName(ctx, name)
}

// GetFeatureHierarchy is the resolver for the getFeatureHierarchy field.
func (r *queryResolver) GetFeatureHierarchy(ctx context.Context, module *string) ([]*features.FeatureHierarchy, error) {
	return r.FeatureResolver.GetFeatureHierarchy(ctx, module)
}

// CheckUserFeature is the resolver for the checkUserFeature field.
func (r *queryResolver) CheckUserFeature(ctx context.Context, input features.FeatureCheckInput) (*features.FeatureCheckResult, error) {
	return r.FeatureResolver.CheckUserFeature(ctx, input)
}

// CheckUserFeatures is the resolver for the checkUserFeatures field.
func (r *queryResolver) CheckUserFeatures(ctx context.Context, input features.BatchFeatureCheckInput) (*features.BatchFeatureCheckResult, error) {
	return r.FeatureResolver.CheckUserFeatures(ctx, input)
}

// GetUserFeatures is the resolver for the getUserFeatures field.
func (r *queryResolver) GetUserFeatures(ctx context.Context, userID string, scope *features.FeatureScopeInput) (*features.UserFeatureSet, error) {
	return r.FeatureResolver.GetUserFeatures(ctx, userID, scope)
}

// GetUserFeatureOverrides is the resolver for the getUserFeatureOverrides field.
func (r *queryResolver) GetUserFeatureOverrides(ctx context.Context, userID string) ([]*features.UserFeature, error) {
	return r.FeatureResolver.GetUserFeatureOverrides(ctx, userID)
}

// GetRoleFeatures is the resolver for the getRoleFeatures field.
func (r *queryResolver) GetRoleFeatures(ctx context.Context, roleName string) ([]*features.RoleFeature, error) {
	return r.FeatureResolver.GetRoleFeatures(ctx, roleName)
}

// GetFeatureStats is the resolver for the getFeatureStats field.
func (r *queryResolver) GetFeatureStats(ctx context.Context) (*features.FeatureStats, error) {
	return r.FeatureResolver.GetFeatureStats(ctx)
}

// =============================================================================
// Mutation Resolvers
// =============================================================================

// CreateFeature is the resolver for the createFeature field.
func (r *mutationResolver) CreateFeature(ctx context.Context, input features.CreateFeatureInput) (*features.Feature, error) {
	return r.FeatureResolver.CreateFeature(ctx, input)
}

// UpdateFeature is the resolver for the updateFeature field.
func (r *mutationResolver) UpdateFeature(ctx context.Context, input features.UpdateFeatureInput) (*features.Feature, error) {
	return r.FeatureResolver.UpdateFeature(ctx, input)
}

// DeleteFeature is the resolver for the deleteFeature field.
func (r *mutationResolver) DeleteFeature(ctx context.Context, id string) (bool, error) {
	return r.FeatureResolver.DeleteFeature(ctx, id)
}

// GrantUserFeature is the resolver for the grantUserFeature field.
func (r *mutationResolver) GrantUserFeature(ctx context.Context, input features.GrantUserFeatureInput) (*features.UserFeature, error) {
	return r.FeatureResolver.GrantUserFeature(ctx, input)
}

// DenyUserFeature is the resolver for the denyUserFeature field.
func (r *mutationResolver) DenyUserFeature(ctx context.Context, input features.DenyUserFeatureInput) (*features.UserFeature, error) {
	return r.FeatureResolver.DenyUserFeature(ctx, input)
}

// RevokeUserFeature is the resolver for the revokeUserFeature field.
func (r *mutationResolver) RevokeUserFeature(ctx context.Context, input features.RevokeUserFeatureInput) (bool, error) {
	return r.FeatureResolver.RevokeUserFeature(ctx, input)
}

// ClearUserFeatures is the resolver for the clearUserFeatures field.
func (r *mutationResolver) ClearUserFeatures(ctx context.Context, userID string) (bool, error) {
	return r.FeatureResolver.ClearUserFeatures(ctx, userID)
}

// AssignRoleFeatures is the resolver for the assignRoleFeatures field.
func (r *mutationResolver) AssignRoleFeatures(ctx context.Context, input features.AssignRoleFeaturesInput) ([]*features.RoleFeature, error) {
	return r.FeatureResolver.AssignRoleFeatures(ctx, input)
}

// RemoveRoleFeatures is the resolver for the removeRoleFeatures field.
func (r *mutationResolver) RemoveRoleFeatures(ctx context.Context, roleName string, features []string) (bool, error) {
	return r.FeatureResolver.RemoveRoleFeatures(ctx, roleName, features)
}

// BulkGrantUserFeatures is the resolver for the bulkGrantUserFeatures field.
func (r *mutationResolver) BulkGrantUserFeatures(ctx context.Context, userIDs []string, features []string, scope *features.FeatureScopeInput, reason *string) ([]*features.UserFeature, error) {
	return r.FeatureResolver.BulkGrantUserFeatures(ctx, userIDs, features, scope, reason)
}

// =============================================================================
// Subscription Resolvers
// =============================================================================

// FeatureUpdates is the resolver for the featureUpdates field.
func (r *subscriptionResolver) FeatureUpdates(ctx context.Context) (<-chan *features.FeatureUpdateEvent, error) {
	// TODO: Implement subscription logic
	// This would require WebSocket infrastructure
	// For now, return a channel that never emits
	ch := make(chan *features.FeatureUpdateEvent)
	return ch, nil
}

// UserFeatureUpdates is the resolver for the userFeatureUpdates field.
func (r *subscriptionResolver) UserFeatureUpdates(ctx context.Context, userID string) (<-chan *features.UserFeatureUpdateEvent, error) {
	// TODO: Implement subscription logic
	// This would require WebSocket infrastructure
	// For now, return a channel that never emits
	ch := make(chan *features.UserFeatureUpdateEvent)
	return ch, nil
}
