package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"agrinovagraphql/server/internal/graphql/generated"
	"agrinovagraphql/server/internal/grading/models"
	"context"
)

// CreateGradingRecord is the resolver for the createGradingRecord field.
func (r *mutationResolver) CreateGradingRecord(ctx context.Context, input generated.CreateGradingRecordInput) (*models.GradingRecord, error) {
	// TODO: Add scope validation here (e.g., require "grading:create")
	// For now, assuming middleware handles authentication

	return r.GradingService.CreateGradingRecord(ctx, input)
}

// UpdateGradingRecord is the resolver for the updateGradingRecord field.
func (r *mutationResolver) UpdateGradingRecord(ctx context.Context, id string, input generated.UpdateGradingRecordInput) (*models.GradingRecord, error) {
	// TODO: Add scope validation here (e.g., require "grading:update")
	// For now, assuming middleware handles authentication

	return r.GradingService.UpdateGradingRecord(ctx, id, input)
}

// ApproveGrading is the resolver for the approveGrading field.
func (r *mutationResolver) ApproveGrading(ctx context.Context, id string, input generated.GradingApprovalInput) (*models.GradingRecord, error) {
	// TODO: Add scope validation here (e.g., require "quality:approve")
	// For now, assuming middleware handles authentication

	return r.GradingService.ApproveGrading(ctx, id, input)
}

// RejectGrading is the resolver for the rejectGrading field.
func (r *mutationResolver) RejectGrading(ctx context.Context, id string, input generated.GradingApprovalInput) (*models.GradingRecord, error) {
	// TODO: Add scope validation here (e.g., require "quality:reject")
	// For now, assuming middleware handles authentication

	return r.GradingService.RejectGrading(ctx, id, input)
}

// GradingRecords is the resolver for the gradingRecords field.
func (r *queryResolver) GradingRecords(ctx context.Context) ([]*models.GradingRecord, error) {
	// TODO: Add scope validation here (e.g., require "grading:read")
	return r.GradingService.ListGradingRecords(ctx)
}

// GradingRecord is the resolver for the gradingRecord field.
func (r *queryResolver) GradingRecord(ctx context.Context, id string) (*models.GradingRecord, error) {
	// TODO: Add scope validation here (e.g., require "grading:read")
	return r.GradingService.GetGradingRecord(ctx, id)
}

// GradingRecordsByHarvest is the resolver for the gradingRecordsByHarvest field.
func (r *queryResolver) GradingRecordsByHarvest(ctx context.Context, harvestRecordId string) ([]*models.GradingRecord, error) {
	// TODO: Add scope validation here (e.g., require "grading:read")
	return r.GradingService.GetGradingRecordsByHarvest(ctx, harvestRecordId)
}

// PendingGradingApprovals is the resolver for the pendingGradingApprovals field.
func (r *queryResolver) PendingGradingApprovals(ctx context.Context) ([]*models.GradingRecord, error) {
	// TODO: Add scope validation here (e.g., require "quality:approve")
	return r.GradingService.GetPendingApprovals(ctx)
}

// GradingUpdated is the resolver for the gradingUpdated field.
func (r *subscriptionResolver) GradingUpdated(ctx context.Context) (<-chan *models.GradingRecord, error) {
	// TODO: Add scope validation here (e.g., require "grading:read")
	return r.GradingService.SubscribeToGradingUpdates(ctx)
}

// GradingApproved is the resolver for the gradingApproved field.
func (r *subscriptionResolver) GradingApproved(ctx context.Context) (<-chan *models.GradingRecord, error) {
	// TODO: Add scope validation here (e.g., require "quality:approve")
	return r.GradingService.SubscribeToGradingApprovals(ctx)
}

// GradingRejected is the resolver for the gradingRejected field.
func (r *subscriptionResolver) GradingRejected(ctx context.Context) (<-chan *models.GradingRecord, error) {
	// TODO: Add scope validation here (e.g., require "quality:reject")
	return r.GradingService.SubscribeToGradingRejections(ctx)
}