package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"agrinovagraphql/server/internal/graphql/domain/asisten"
	"agrinovagraphql/server/internal/graphql/domain/auth"
	"agrinovagraphql/server/internal/graphql/domain/common"
	"agrinovagraphql/server/internal/graphql/domain/mandor"
	"agrinovagraphql/server/internal/graphql/domain/master"
	"agrinovagraphql/server/internal/graphql/generated"
	"agrinovagraphql/server/internal/middleware"
	panenModels "agrinovagraphql/server/internal/panen/models"
	"context"
	"errors"
	"fmt"
	"log"
	"strings"
	"time"

	"gorm.io/gorm"
)

// CreateMandorHarvest is the resolver for the createMandorHarvest field.
func (r *mutationResolver) CreateMandorHarvest(ctx context.Context, input mandor.CreateMandorHarvestInput) (*mandor.MandorHarvestResult, error) {
	// 1. Get MandorID from context (authenticated user)
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return nil, fmt.Errorf("authentication required")
	}

	// 2. Check for existing record by LocalID (Idempotency)
	// input.LocalID is String! in schema, so it is a value, not pointer
	if input.LocalID != "" {
		existing, err := r.PanenResolver.GetByLocalID(ctx, input.LocalID, userID)
		if err == nil && existing != nil {
			// Already exists, return successful result with existing data
			return &mandor.MandorHarvestResult{
				Success:       true,
				Message:       "Record already exists",
				HarvestRecord: convertToMandorHarvestRecord((*mandor.HarvestRecord)(existing)),
				ServerID:      &existing.ID,
			}, nil
		}
	}

	// 3. Handle optional fields
	// BeratTbs is *float64 in CreateMandorHarvestInput (optional)
	var beratTbs float64
	if input.BeratTbs != nil {
		beratTbs = *input.BeratTbs
	}

	// Prepare input for creation
	// CreateHarvestRecordInput.LocalID expects *string
	// Convert string value to pointer
	var localIDPtr *string
	if input.LocalID != "" {
		localID := input.LocalID
		localIDPtr = &localID
	}

	createInput := mandor.CreateHarvestRecordInput{
		LocalID:       localIDPtr,
		DeviceID:      stringPointerIfNotEmpty(input.DeviceID),
		Tanggal:       input.Tanggal,
		MandorID:      userID, // Use authenticated user ID
		BlockID:       input.BlockID,
		Karyawan:      input.Karyawan,
		JumlahJanjang: int32(input.JumlahJanjang),
		BeratTbs:      beratTbs,
	}

	// Create new record
	newRecord, err := r.PanenResolver.CreateHarvestRecord(ctx, createInput)
	if err != nil {
		return &mandor.MandorHarvestResult{
			Success: false,
			Message: err.Error(),
			Errors:  []string{err.Error()},
		}, nil
	}
	r.notifyAsistenHarvestCreated(ctx, newRecord)
	publishHarvestRecordCreated((*mandor.HarvestRecord)(newRecord))

	return &mandor.MandorHarvestResult{
		Success:       true,
		Message:       "Harvest record created successfully",
		HarvestRecord: convertToMandorHarvestRecord((*mandor.HarvestRecord)(newRecord)),
		ServerID:      &newRecord.ID,
	}, nil
}

// UpdateMandorHarvest is the resolver for the updateMandorHarvest field.
func (r *mutationResolver) UpdateMandorHarvest(ctx context.Context, input mandor.UpdateMandorHarvestInput) (*mandor.MandorHarvestResult, error) {
	panic(fmt.Errorf("not implemented: UpdateMandorHarvest - updateMandorHarvest"))
}

// DeleteMandorHarvest is the resolver for the deleteMandorHarvest field.
func (r *mutationResolver) DeleteMandorHarvest(ctx context.Context, id string, deviceID string) (*mandor.MandorHarvestResult, error) {
	panic(fmt.Errorf("not implemented: DeleteMandorHarvest - deleteMandorHarvest"))
}

// SyncMandorHarvests is the resolver for the syncMandorHarvests field.
func (r *mutationResolver) SyncMandorHarvests(ctx context.Context, input mandor.MandorSyncInput) (*mandor.MandorSyncResult, error) {
	panic(fmt.Errorf("not implemented: SyncMandorHarvests - syncMandorHarvests"))
}

// SyncMandorPhotos is the resolver for the syncMandorPhotos field.
func (r *mutationResolver) SyncMandorPhotos(ctx context.Context, input mandor.MandorPhotoSyncInput) (*mandor.MandorPhotoSyncResult, error) {
	panic(fmt.Errorf("not implemented: SyncMandorPhotos - syncMandorPhotos"))
}

// MarkMandorSyncCompleted is the resolver for the markMandorSyncCompleted field.
func (r *mutationResolver) MarkMandorSyncCompleted(ctx context.Context, deviceID string, transactionID string) (bool, error) {
	panic(fmt.Errorf("not implemented: MarkMandorSyncCompleted - markMandorSyncCompleted"))
}

// CreateHarvestRecord is the resolver for the createHarvestRecord field.
func (r *mutationResolver) CreateHarvestRecord(ctx context.Context, input mandor.CreateHarvestRecordInput) (*mandor.HarvestRecord, error) {
	// Convert internal models.HarvestRecord to mandor.HarvestRecord
	harvestModel, err := r.PanenResolver.CreateHarvestRecord(ctx, input)
	if err != nil {
		return nil, err
	}
	r.notifyAsistenHarvestCreated(ctx, harvestModel)
	publishHarvestRecordCreated((*mandor.HarvestRecord)(harvestModel))

	// Convert to GraphQL generated type
	return (*mandor.HarvestRecord)(harvestModel), nil
}

// UpdateHarvestRecord is the resolver for the updateHarvestRecord field.
func (r *mutationResolver) UpdateHarvestRecord(ctx context.Context, input mandor.UpdateHarvestRecordInput) (*mandor.HarvestRecord, error) {
	harvestModel, err := r.PanenResolver.UpdateHarvestRecord(ctx, input)
	if err != nil {
		return nil, err
	}

	return (*mandor.HarvestRecord)(harvestModel), nil
}

// ApproveHarvestRecord is the resolver for the approveHarvestRecord field.
func (r *mutationResolver) ApproveHarvestRecord(ctx context.Context, input asisten.ApproveHarvestInput) (*mandor.HarvestRecord, error) {
	currentUserID := strings.TrimSpace(middleware.GetCurrentUserID(ctx))
	if currentUserID == "" {
		return nil, fmt.Errorf("authentication required")
	}

	currentRole := middleware.GetUserRoleFromContext(ctx)
	if currentRole == auth.UserRoleManager {
		if err := r.ensureManagerCanAccessHarvest(ctx, currentUserID, input.ID); err != nil {
			return nil, err
		}
	}

	effectiveInput := input
	effectiveInput.ApprovedBy = currentUserID

	harvestModel, err := r.PanenResolver.ApproveHarvestRecord(ctx, effectiveInput)
	if err != nil {
		return nil, err
	}
	r.notifyMandorHarvestApproved(ctx, harvestModel, currentUserID)
	publishHarvestRecordApproved((*mandor.HarvestRecord)(harvestModel))

	return (*mandor.HarvestRecord)(harvestModel), nil
}

// RejectHarvestRecord is the resolver for the rejectHarvestRecord field.
func (r *mutationResolver) RejectHarvestRecord(ctx context.Context, input asisten.RejectHarvestInput) (*mandor.HarvestRecord, error) {
	currentUserID := strings.TrimSpace(middleware.GetCurrentUserID(ctx))
	if currentUserID == "" {
		return nil, fmt.Errorf("authentication required")
	}

	currentRole := middleware.GetUserRoleFromContext(ctx)
	if currentRole == auth.UserRoleManager {
		if err := r.ensureManagerCanAccessHarvest(ctx, currentUserID, input.ID); err != nil {
			return nil, err
		}
	}

	harvestModel, err := r.PanenResolver.RejectHarvestRecord(ctx, input)
	if err != nil {
		return nil, err
	}
	r.notifyMandorHarvestRejected(ctx, harvestModel, input.RejectedReason, currentUserID)
	publishHarvestRecordRejected((*mandor.HarvestRecord)(harvestModel))

	return (*mandor.HarvestRecord)(harvestModel), nil
}

// DeleteHarvestRecord is the resolver for the deleteHarvestRecord field.
func (r *mutationResolver) DeleteHarvestRecord(ctx context.Context, id string) (bool, error) {
	return r.PanenResolver.DeleteHarvestRecord(ctx, id)
}

// SyncHarvestRecords is the resolver for the syncHarvestRecords field.
// Supports both CREATE (new records) and UPDATE (existing records with serverId)
func (r *mutationResolver) SyncHarvestRecords(ctx context.Context, input mandor.HarvestSyncInput) (*mandor.MandorSyncResult, error) {
	authUserID := strings.TrimSpace(middleware.GetCurrentUserID(ctx))
	if authUserID == "" {
		return nil, fmt.Errorf("authentication required")
	}

	successCount := 0
	failureCount := 0
	conflictsDetected := 0
	createdCount := 0
	updatedCount := 0
	var createdNotificationBatch []*panenModels.HarvestRecord
	var syncResults []*mandor.MandorSyncItemResult

	stringValue := func(value *string) string {
		if value == nil {
			return ""
		}
		return strings.TrimSpace(*value)
	}

	log.Printf(
		"[SyncHarvestRecords] deviceId=%s clientTimestamp=%s records=%d",
		strings.TrimSpace(input.DeviceID),
		input.ClientTimestamp.Format(time.RFC3339),
		len(input.Records),
	)
	syncLookupCtx := r.PanenResolver.WithSyncLookupCache(ctx)

	for _, recordInput := range input.Records {
		if recordInput == nil {
			failureCount++
			errMsg := "invalid sync record: payload item is null"
			syncResults = append(syncResults, &mandor.MandorSyncItemResult{
				Success: false,
				Status:  common.SyncItemStatusRejected,
				Error:   &errMsg,
			})
			continue
		}

		var err error
		var record *mandor.HarvestRecord
		var createdModel *panenModels.HarvestRecord
		recordCreated := false
		recordUpdated := false
		recordConflict := false
		conflictResolutionFailed := false
		effectiveMandorID := authUserID
		effectiveDeviceID := strings.TrimSpace(input.DeviceID)
		effectiveKaryawanID := normalizeSyncKaryawanID(recordInput.KaryawanID)
		effectiveEmployeeDivisionID := normalizeSyncOptionalUUID(recordInput.EmployeeDivisionID)
		effectiveEmployeeDivisionName := normalizeSyncOptionalText(recordInput.EmployeeDivisionName)
		if effectiveKaryawanID == nil {
			errMsg := "invalid karyawanId: must be a UUID"
			syncResults = append(syncResults, &mandor.MandorSyncItemResult{
				LocalID:  recordInput.LocalID,
				ServerID: recordInput.ServerID,
				Success:  false,
				Status:   common.SyncItemStatusRejected,
				Error:    &errMsg,
			})
			failureCount++
			continue
		}

		effectiveNik := normalizeSyncNik(recordInput.Nik)
		if effectiveNik == nil {
			errMsg := "invalid nik: must not be empty"
			syncResults = append(syncResults, &mandor.MandorSyncItemResult{
				LocalID:  recordInput.LocalID,
				ServerID: recordInput.ServerID,
				Success:  false,
				Status:   common.SyncItemStatusRejected,
				Error:    &errMsg,
			})
			failureCount++
			continue
		}

		err = r.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
			scopedPanenResolver := r.PanenResolver.WithDB(tx)
			isUpdate := false

			// Determine if this is an UPDATE or CREATE based on ServerID presence.
			if recordInput.ServerID != nil && *recordInput.ServerID != "" {
				isUpdate = true
				existing, findErr := scopedPanenResolver.GetHarvestRecordLight(syncLookupCtx, *recordInput.ServerID)
				if findErr != nil || existing == nil {
					// Server record not found - fall back to create path.
					isUpdate = false
				} else {
					if strings.TrimSpace(existing.MandorID) != effectiveMandorID {
						return fmt.Errorf("access denied: cannot sync another mandor's harvest record")
					}

					isConflict, conflictErr := r.checkAndResolveConflict(
						syncLookupCtx,
						(*panenModels.HarvestRecord)(existing),
						recordInput,
						effectiveDeviceID,
						effectiveKaryawanID,
						effectiveNik,
					)
					if conflictErr != nil {
						conflictResolutionFailed = true
						return fmt.Errorf("conflict resolution failed: %w", conflictErr)
					}

					if isConflict {
						recordConflict = true
						// Server wins - return existing record without write.
						record = existing
						return nil
					}

					// No conflict - allow updates for:
					// 1) normal draft update (PENDING -> PENDING)
					// 2) correction flow (REJECTED -> PENDING)
					existingStatus := strings.ToUpper(strings.TrimSpace(string(existing.Status)))
					requestedStatus := strings.ToUpper(strings.TrimSpace(stringValue(recordInput.Status)))
					allowRejectedCorrection := existingStatus == "REJECTED" && requestedStatus == "PENDING"
					if existingStatus != "PENDING" && !allowRejectedCorrection {
						return fmt.Errorf("cannot update record with status %s", existing.Status)
					}

					updatedRecord, updateErr := r.updateHarvestRecordFromSync(
						syncLookupCtx,
						scopedPanenResolver,
						*recordInput.ServerID,
						recordInput,
						effectiveDeviceID,
						effectiveKaryawanID,
						effectiveNik,
						effectiveEmployeeDivisionID,
						effectiveEmployeeDivisionName,
						allowRejectedCorrection,
					)
					if updateErr != nil {
						return updateErr
					}

					record = updatedRecord
					recordUpdated = true
					return nil
				}
			}

			// CREATE: No server ID or server record not found.
			if !isUpdate {
				existing, findErr := scopedPanenResolver.GetByLocalIDLight(syncLookupCtx, recordInput.LocalID, effectiveMandorID)
				if findErr == nil && existing != nil {
					// Record already exists by LocalID - treat as success (idempotent).
					record = (*mandor.HarvestRecord)(existing)
					return nil
				}

				localID := recordInput.LocalID
				var localIDPtr *string
				if localID != "" {
					localIDPtr = &localID
				}

				createInput := mandor.CreateHarvestRecordInput{
					LocalID:       localIDPtr,
					DeviceID:      stringPointerIfNotEmpty(effectiveDeviceID),
					Tanggal:       recordInput.Tanggal,
					MandorID:      effectiveMandorID,
					BlockID:       recordInput.BlockID,
					Karyawan:      *effectiveNik,
					JumlahJanjang: int32(recordInput.JumlahJanjang),
					BeratTbs:      recordInput.BeratTbs,
				}

				// Add optional fields from sync input.
				if recordInput.Notes != nil {
					createInput.Notes = recordInput.Notes
				}
				if recordInput.JjgMatang != nil {
					createInput.JjgMatang = recordInput.JjgMatang
				}
				if recordInput.JjgMentah != nil {
					createInput.JjgMentah = recordInput.JjgMentah
				}
				if recordInput.JjgLewatMatang != nil {
					createInput.JjgLewatMatang = recordInput.JjgLewatMatang
				}
				if recordInput.JjgBusukAbnormal != nil {
					createInput.JjgBusukAbnormal = recordInput.JjgBusukAbnormal
				}
				if recordInput.JjgTangkaiPanjang != nil {
					createInput.JjgTangkaiPanjang = recordInput.JjgTangkaiPanjang
				}
				if recordInput.TotalBrondolan != nil {
					createInput.TotalBrondolan = recordInput.TotalBrondolan
				}
				if recordInput.Latitude != nil {
					createInput.Latitude = recordInput.Latitude
				}
				if recordInput.Longitude != nil {
					createInput.Longitude = recordInput.Longitude
				}
				if recordInput.CompanyID != nil {
					createInput.CompanyID = recordInput.CompanyID
				}
				if recordInput.EstateID != nil {
					createInput.EstateID = recordInput.EstateID
				}
				if recordInput.DivisionID != nil {
					createInput.DivisionID = recordInput.DivisionID
				}
				if effectiveEmployeeDivisionID != nil {
					createInput.EmployeeDivisionID = effectiveEmployeeDivisionID
				}
				if effectiveEmployeeDivisionName != nil {
					createInput.EmployeeDivisionName = effectiveEmployeeDivisionName
				}
				createInput.KaryawanID = effectiveKaryawanID

				if recordInput.PhotoURL != nil {
					photoValue := strings.TrimSpace(*recordInput.PhotoURL)
					if photoValue != "" {
						resolvedPhotoURL, photoErr := r.saveHarvestPhotoFromPayload(recordInput.LocalID, photoValue)
						if photoErr != nil {
							return fmt.Errorf("failed to process harvest photo: %w", photoErr)
						}
						createInput.PhotoURL = &resolvedPhotoURL
					}
				}

				model, createErr := scopedPanenResolver.CreateHarvestRecordForSync(syncLookupCtx, createInput)
				if createErr != nil {
					return createErr
				}
				record = (*mandor.HarvestRecord)(model)
				createdModel = model
				recordCreated = true
			}

			return nil
		})

		itemResult := &mandor.MandorSyncItemResult{
			LocalID: recordInput.LocalID,
		}

		if err != nil {
			failureCount++
			if conflictResolutionFailed {
				conflictsDetected++
			}
			errMsg := err.Error()
			itemResult.Success = false
			itemResult.Status = common.SyncItemStatusRejected
			itemResult.Error = &errMsg
		} else {
			successCount++
			if recordConflict {
				conflictsDetected++
			}
			if recordUpdated {
				updatedCount++
			}
			if recordCreated {
				createdCount++
				createdNotificationBatch = append(createdNotificationBatch, createdModel)
				publishHarvestRecordCreated((*mandor.HarvestRecord)(createdModel))
			}
			itemResult.Success = true
			itemResult.Status = common.SyncItemStatusAccepted
			if record != nil {
				itemResult.ServerID = &record.ID
			}
		}
		syncResults = append(syncResults, itemResult)
	}

	if len(createdNotificationBatch) == 1 {
		r.notifyAsistenHarvestCreated(ctx, createdNotificationBatch[0])
	} else if len(createdNotificationBatch) > 1 {
		r.notifyAsistenHarvestCreatedBatch(ctx, createdNotificationBatch)
	}

	transactionID := fmt.Sprintf("txn_%d", time.Now().UnixNano())

	// Build detailed message
	message := fmt.Sprintf("Processed %d records (%d created, %d updated)", len(input.Records), createdCount, updatedCount)
	if conflictsDetected > 0 {
		message = fmt.Sprintf("%s, %d conflicts resolved", message, conflictsDetected)
	}

	return &mandor.MandorSyncResult{
		Success:           failureCount == 0,
		TransactionID:     transactionID,
		RecordsProcessed:  int32(len(input.Records)),
		RecordsSuccessful: int32(successCount),
		RecordsFailed:     int32(failureCount),
		ConflictsDetected: int32(conflictsDetected),
		Results:           syncResults,
		ServerTimestamp:   time.Now(),
		Message:           message,
	}, nil
}

// MandorDashboard is the resolver for the mandorDashboard field.
func (r *queryResolver) MandorDashboard(ctx context.Context) (*mandor.MandorDashboardData, error) {
	// Get the authenticated user's ID from context
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return nil, fmt.Errorf("user not authenticated")
	}

	// Get dashboard stats
	stats, err := r.PanenResolver.GetMandorDashboardStats(ctx, userID)
	if err != nil {
		return nil, err
	}

	// Get recent activities
	activities, err := r.PanenResolver.GetMandorActivities(ctx, userID, 5)
	if err != nil {
		activities = []*mandor.MandorActivity{}
	}

	// Build dashboard data (some fields need additional queries)
	return &mandor.MandorDashboardData{
		User:               nil, // Would need to fetch user details
		Divisions:          []*master.Division{},
		Stats:              stats,
		RecentActivities:   activities,
		PendingSubmissions: []*mandor.MandorHarvestSummary{},
		TodayWork: &mandor.MandorTodayWork{
			HarvestsCreated: stats.TodayHarvestCount,
			TotalTbs:        stats.TodayTbsCount,
			TotalWeight:     stats.TodayWeight,
			WorkersInvolved: stats.ActiveWorkers,
			BlocksCompleted: stats.BlocksWorkedToday,
		},
		SyncStatus: &mandor.MandorSyncStatus{
			IsOnline:            true,
			PendingSyncCount:    0,
			FailedSyncCount:     0,
			PhotosPendingUpload: 0,
		},
	}, nil
}

// MandorDashboardStats is the resolver for the mandorDashboardStats field.
func (r *queryResolver) MandorDashboardStats(ctx context.Context) (*mandor.MandorDashboardStats, error) {
	// Get the authenticated user's ID from context
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return nil, fmt.Errorf("user not authenticated")
	}

	return r.PanenResolver.GetMandorDashboardStats(ctx, userID)
}

// MandorActivities is the resolver for the mandorActivities field.
func (r *queryResolver) MandorActivities(ctx context.Context, limit *int32) ([]*mandor.MandorActivity, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return nil, fmt.Errorf("user not authenticated")
	}

	limitVal := 20
	if limit != nil && *limit > 0 {
		limitVal = int(*limit)
	}

	return r.PanenResolver.GetMandorActivities(ctx, userID, limitVal)
}

// MandorSyncStatus is the resolver for the mandorSyncStatus field.
func (r *queryResolver) MandorSyncStatus(ctx context.Context) (*mandor.MandorSyncStatus, error) {
	// Sync status is primarily client-side state
	// Server returns default values indicating no pending server-side operations
	return &mandor.MandorSyncStatus{
		IsOnline:            true,
		LastSyncAt:          nil,
		PendingSyncCount:    0,
		FailedSyncCount:     0,
		LastSyncResult:      nil,
		PhotosPendingUpload: 0,
	}, nil
}

// MandorBlocks is the resolver for the mandorBlocks field.
func (r *queryResolver) MandorBlocks(ctx context.Context, divisionID *string) ([]*master.Block, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return nil, fmt.Errorf("user not authenticated")
	}

	assignedDivisionIDs, err := r.getMandorAssignedDivisionIDs(ctx, userID)
	if err != nil {
		return nil, err
	}

	// If no division assignments, return empty list
	if len(assignedDivisionIDs) == 0 {
		return []*master.Block{}, nil
	}

	// Query blocks available to this mandor
	var blocks []*master.Block
	query := r.db.WithContext(ctx).Model(&master.Block{})
	query, err = r.applyMandorDivisionScope(query, assignedDivisionIDs, divisionID, "division_id")
	if err != nil {
		return nil, err
	}

	if err := query.Where("is_active = ?", true).Find(&blocks).Error; err != nil {
		return nil, fmt.Errorf("failed to get blocks: %w", err)
	}

	return blocks, nil
}

// MandorEmployees is the resolver for the mandorEmployees field.
func (r *queryResolver) MandorEmployees(ctx context.Context, divisionID *string, search *string) ([]*master.Employee, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return nil, fmt.Errorf("user not authenticated")
	}

	assignedDivisionIDs, err := r.getMandorAssignedDivisionIDs(ctx, userID)
	if err != nil {
		return nil, err
	}
	if len(assignedDivisionIDs) == 0 {
		return []*master.Employee{}, nil
	}

	// Get user's company_id from context
	companyID, _ := ctx.Value("company_id").(string)

	// Query employees available to this mandor
	var employees []*master.Employee
	query := r.db.WithContext(ctx).Model(&master.Employee{})

	// Filter by company (employees belong to same company as mandor)
	if companyID != "" {
		query = query.Where("company_id = ?", companyID)
	}

	query, err = r.applyMandorDivisionScope(query, assignedDivisionIDs, divisionID, "division_id")
	if err != nil {
		return nil, err
	}

	// Search by name or NIK
	if search != nil && *search != "" {
		searchPattern := "%" + *search + "%"
		query = query.Where("name ILIKE ? OR nik ILIKE ?", searchPattern, searchPattern)
	}

	query = query.Where("is_active = ?", true).Order("id ASC")

	// Internal pagination to avoid hard cap/truncation and still keep query memory-friendly.
	const pageSize = 200
	offset := 0
	for {
		var batch []*master.Employee
		if err := query.Offset(offset).Limit(pageSize).Find(&batch).Error; err != nil {
			return nil, fmt.Errorf("failed to get employees: %w", err)
		}
		if len(batch) == 0 {
			break
		}

		employees = append(employees, batch...)
		offset += len(batch)
		if len(batch) < pageSize {
			break
		}
	}

	return employees, nil
}

// MandorDivisionMastersSync is the resolver for the mandorDivisionMastersSync field.
func (r *queryResolver) MandorDivisionMastersSync(ctx context.Context, updatedSince time.Time) (*auth.UserAssignments, error) {
	assignments, err := r.MasterResolver.GetMyAssignments(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get assignment masters: %w", err)
	}

	result := &auth.UserAssignments{
		Companies: make([]*master.Company, 0),
		Estates:   make([]*master.Estate, 0),
		Divisions: make([]*master.Division, 0),
		Blocks:    make([]*master.Block, 0),
	}

	if assignments == nil {
		return result, nil
	}

	for _, company := range assignments.Companies {
		if company != nil && company.UpdatedAt.After(updatedSince) {
			result.Companies = append(result.Companies, company)
		}
	}

	for _, estate := range assignments.Estates {
		if estate != nil && estate.UpdatedAt.After(updatedSince) {
			result.Estates = append(result.Estates, estate)
		}
	}

	for _, division := range assignments.Divisions {
		if division != nil && division.UpdatedAt.After(updatedSince) {
			result.Divisions = append(result.Divisions, division)
		}
	}

	return result, nil
}

// MandorBlocksSync is the resolver for the mandorBlocksSync field.
func (r *queryResolver) MandorBlocksSync(ctx context.Context, divisionID *string, updatedSince time.Time) ([]*master.Block, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return nil, fmt.Errorf("user not authenticated")
	}

	assignedDivisionIDs, err := r.getMandorAssignedDivisionIDs(ctx, userID)
	if err != nil {
		return nil, err
	}
	if len(assignedDivisionIDs) == 0 {
		return []*master.Block{}, nil
	}

	var blocks []*master.Block
	query := r.db.WithContext(ctx).Model(&master.Block{})
	query, err = r.applyMandorDivisionScope(query, assignedDivisionIDs, divisionID, "division_id")
	if err != nil {
		return nil, err
	}

	if err := query.
		Where("updated_at > ?", updatedSince).
		Order("updated_at ASC").
		Find(&blocks).Error; err != nil {
		return nil, fmt.Errorf("failed to get incremental blocks: %w", err)
	}

	return blocks, nil
}

// MandorEmployeesSync is the resolver for the mandorEmployeesSync field.
func (r *queryResolver) MandorEmployeesSync(ctx context.Context, divisionID *string, updatedSince time.Time) ([]*master.Employee, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return nil, fmt.Errorf("user not authenticated")
	}

	assignedDivisionIDs, err := r.getMandorAssignedDivisionIDs(ctx, userID)
	if err != nil {
		return nil, err
	}
	if len(assignedDivisionIDs) == 0 {
		return []*master.Employee{}, nil
	}

	companyID, _ := ctx.Value("company_id").(string)
	var employees []*master.Employee
	query := r.db.WithContext(ctx).Model(&master.Employee{})
	if companyID != "" {
		query = query.Where("company_id = ?", companyID)
	}

	query, err = r.applyMandorDivisionScope(query, assignedDivisionIDs, divisionID, "division_id")
	if err != nil {
		return nil, err
	}

	if err := query.
		Where("updated_at > ?", updatedSince).
		Order("updated_at ASC").
		Find(&employees).Error; err != nil {
		return nil, fmt.Errorf("failed to get incremental employees: %w", err)
	}

	return employees, nil
}

// MandorHistory is the resolver for the mandorHistory field.
func (r *queryResolver) MandorHistory(ctx context.Context, filter *mandor.MandorHistoryFilter) (*mandor.MandorHistoryResponse, error) {
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return nil, fmt.Errorf("user not authenticated")
	}

	return r.PanenResolver.GetMandorHistory(ctx, userID, filter)
}

// MandorHarvestRecord is the resolver for the mandorHarvestRecord field.
func (r *queryResolver) MandorHarvestRecord(ctx context.Context, id string) (*mandor.MandorHarvestRecord, error) {
	// Get the harvest record using existing resolver
	record, err := r.PanenResolver.HarvestRecord(ctx, id)
	if err != nil {
		return nil, err
	}
	if record == nil {
		return nil, nil
	}

	// Convert to MandorHarvestRecord
	return convertToMandorHarvestRecord(record), nil
}

// MandorPendingSyncItems is the resolver for the mandorPendingSyncItems field.
func (r *queryResolver) MandorPendingSyncItems(ctx context.Context, deviceID string) ([]*mandor.MandorPendingSyncItem, error) {
	panic(fmt.Errorf("not implemented: MandorPendingSyncItems - mandorPendingSyncItems"))
}

// MandorServerUpdates is the resolver for the mandorServerUpdates field.
// This returns harvest records that have been updated since the given timestamp.
// Used by mobile app to sync approval status changes from server.
func (r *queryResolver) MandorServerUpdates(ctx context.Context, since time.Time, _ string) ([]*mandor.MandorHarvestRecord, error) {
	// Get the authenticated user's ID from context
	userID, ok := ctx.Value("user_id").(string)
	if !ok || userID == "" {
		return nil, fmt.Errorf("user not authenticated")
	}

	// Query harvest records for this mandor that have been updated since the given time
	records, err := r.PanenResolver.GetHarvestRecordsByMandorSince(ctx, userID, since)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch harvest updates: %w", err)
	}

	// Convert HarvestRecord to MandorHarvestRecord
	result := make([]*mandor.MandorHarvestRecord, len(records))
	for i, record := range records {
		result[i] = convertToMandorHarvestRecord(record)
	}

	return result, nil
}

// HarvestRecords is the resolver for the harvestRecords field.
func (r *queryResolver) HarvestRecords(ctx context.Context, dateFrom *time.Time, dateTo *time.Time) ([]*mandor.HarvestRecord, error) {
	userID, role := getCurrentUserScope(ctx)
	if userID == "" {
		return nil, fmt.Errorf("authentication required")
	}

	var (
		harvestModels []*panenModels.HarvestRecord
		err           error
	)

	// Create filters
	filters := &panenModels.HarvestFilters{
		DateFrom: dateFrom,
		DateTo:   dateTo,
	}

	switch role {
	case auth.UserRoleMandor:
		harvestModels, err = r.PanenResolver.HarvestRecordsByMandor(ctx, userID, filters)
	case auth.UserRoleManager:
		scopedFilters, hasScope, scopeErr := r.buildScopedHarvestFilters(ctx, userID, role, filters)
		if scopeErr != nil {
			return nil, scopeErr
		}
		if hasScope {
			harvestModels, err = r.PanenResolver.HarvestRecords(ctx, scopedFilters)
			break
		}
		harvestModels, err = r.PanenResolver.HarvestRecordsByManager(ctx, userID, filters)
	case auth.UserRoleAsisten, auth.UserRoleAreaManager, auth.UserRoleCompanyAdmin:
		scopedFilters, hasScope, scopeErr := r.buildScopedHarvestFilters(ctx, userID, role, filters)
		if scopeErr != nil {
			return nil, scopeErr
		}
		if hasScope {
			harvestModels, err = r.PanenResolver.HarvestRecords(ctx, scopedFilters)
			break
		}

		hierarchyFilters, hasHierarchyScope, hierarchyErr := r.buildHierarchyMandorScopedHarvestFilters(ctx, userID, filters)
		if hierarchyErr != nil {
			return nil, hierarchyErr
		}
		if !hasHierarchyScope {
			return []*mandor.HarvestRecord{}, nil
		}
		harvestModels, err = r.PanenResolver.HarvestRecords(ctx, hierarchyFilters)
	default:
		harvestModels, err = r.PanenResolver.HarvestRecords(ctx, filters)
	}
	if err != nil {
		return nil, err
	}

	// Convert slice of internal models to slice of generated types
	result := make([]*mandor.HarvestRecord, len(harvestModels))
	for i, model := range harvestModels {
		result[i] = (*mandor.HarvestRecord)(model)
	}

	return result, nil
}

// HarvestRecordsPaginated is the resolver for the harvestRecordsPaginated field.
func (r *queryResolver) HarvestRecordsPaginated(ctx context.Context, page *int32, limit *int32, status *mandor.HarvestStatus, search *string, sortBy *string, sortDir *string, dateFrom *time.Time, dateTo *time.Time) (*generated.HarvestRecordsPaginatedResponse, error) {
	userID, role := getCurrentUserScope(ctx)
	if userID == "" {
		return nil, fmt.Errorf("authentication required")
	}

	// Defaults
	pageVal := int32(1)
	if page != nil && *page > 0 {
		pageVal = *page
	}
	limitVal := int32(10)
	if limit != nil && *limit > 0 {
		limitVal = *limit
		if limitVal > 100 {
			limitVal = 100
		}
	}
	offset := int((pageVal - 1) * limitVal)
	limitInt := int(limitVal)

	// Build filters
	filters := &panenModels.HarvestFilters{
		DateFrom: dateFrom,
		DateTo:   dateTo,
		Status:   status,
		Search:   search,
		OrderBy:  sortBy,
		OrderDir: sortDir,
		Limit:    &limitInt,
		Offset:   &offset,
	}

	// Count filters (same without pagination)
	countFilters := &panenModels.HarvestFilters{
		DateFrom: dateFrom,
		DateTo:   dateTo,
		Status:   status,
		Search:   search,
	}

	var (
		harvestModels []*panenModels.HarvestRecord
		totalCount    int64
		err           error
		countErr      error
	)

	switch role {
	case auth.UserRoleMandor:
		harvestModels, err = r.PanenResolver.HarvestRecordsByMandor(ctx, userID, filters)
		if err == nil {
			mandorCountFilters := *countFilters
			mandorID := userID
			mandorCountFilters.MandorID = &mandorID
			totalCount, countErr = r.PanenResolver.CountHarvestRecords(ctx, &mandorCountFilters)
		}
	case auth.UserRoleManager:
		scopedFilters, hasScope, scopeErr := r.buildScopedHarvestFilters(ctx, userID, role, filters)
		if scopeErr != nil {
			return nil, scopeErr
		}
		if hasScope {
			harvestModels, err = r.PanenResolver.HarvestRecords(ctx, scopedFilters)
			if err == nil {
				scopedCountFilters, _, _ := r.buildScopedHarvestFilters(ctx, userID, role, countFilters)
				totalCount, countErr = r.PanenResolver.CountHarvestRecords(ctx, scopedCountFilters)
			}
		} else {
			harvestModels, err = r.PanenResolver.HarvestRecordsByManager(ctx, userID, filters)
			if err == nil {
				managerCountFilters := *countFilters
				totalCount, countErr = r.PanenResolver.CountHarvestRecords(ctx, &managerCountFilters)
			}
		}
	case auth.UserRoleAsisten, auth.UserRoleAreaManager, auth.UserRoleCompanyAdmin:
		scopedFilters, hasScope, scopeErr := r.buildScopedHarvestFilters(ctx, userID, role, filters)
		if scopeErr != nil {
			return nil, scopeErr
		}
		if hasScope {
			harvestModels, err = r.PanenResolver.HarvestRecords(ctx, scopedFilters)
			if err == nil {
				scopedCountFilters, _, _ := r.buildScopedHarvestFilters(ctx, userID, role, countFilters)
				totalCount, countErr = r.PanenResolver.CountHarvestRecords(ctx, scopedCountFilters)
			}
		} else {
			hierarchyFilters, hasHierarchyScope, hierarchyErr := r.buildHierarchyMandorScopedHarvestFilters(ctx, userID, filters)
			if hierarchyErr != nil {
				return nil, hierarchyErr
			}
			if !hasHierarchyScope {
				return &generated.HarvestRecordsPaginatedResponse{
					Data:       []*mandor.HarvestRecord{},
					TotalCount: 0,
					HasMore:    false,
				}, nil
			}
			harvestModels, err = r.PanenResolver.HarvestRecords(ctx, hierarchyFilters)
			if err == nil {
				hierarchyCountFilters, _, _ := r.buildHierarchyMandorScopedHarvestFilters(ctx, userID, countFilters)
				totalCount, countErr = r.PanenResolver.CountHarvestRecords(ctx, hierarchyCountFilters)
			}
		}
	default:
		harvestModels, err = r.PanenResolver.HarvestRecords(ctx, filters)
		if err == nil {
			totalCount, countErr = r.PanenResolver.CountHarvestRecords(ctx, countFilters)
		}
	}

	if err != nil {
		return nil, err
	}
	if countErr != nil {
		return nil, countErr
	}

	result := make([]*mandor.HarvestRecord, len(harvestModels))
	for i, model := range harvestModels {
		result[i] = (*mandor.HarvestRecord)(model)
	}

	hasMore := int64(offset)+int64(len(result)) < totalCount

	return &generated.HarvestRecordsPaginatedResponse{
		Data:       result,
		TotalCount: int32(totalCount),
		HasMore:    hasMore,
	}, nil
}

// HarvestRecord is the resolver for the harvestRecord field.
func (r *queryResolver) HarvestRecord(ctx context.Context, id string) (*mandor.HarvestRecord, error) {
	userID, role := getCurrentUserScope(ctx)
	if userID == "" {
		return nil, fmt.Errorf("authentication required")
	}

	var (
		harvestModel *panenModels.HarvestRecord
		err          error
	)
	switch role {
	case auth.UserRoleMandor:
		harvestModel, err = r.PanenResolver.HarvestRecord(ctx, id)
		if err != nil {
			return nil, err
		}
		if harvestModel == nil {
			return nil, nil
		}
		if strings.TrimSpace(harvestModel.MandorID) != userID {
			return nil, fmt.Errorf("harvest record not found")
		}
	case auth.UserRoleManager:
		scopedFilters, hasScope, scopeErr := r.buildScopedHarvestFilters(ctx, userID, role, nil)
		if scopeErr != nil {
			return nil, scopeErr
		}
		if hasScope {
			harvestModel, err = r.PanenResolver.HarvestRecord(ctx, id)
			if err != nil {
				return nil, err
			}
			if harvestModel == nil {
				return nil, nil
			}
			if !isHarvestRecordInScopedAssignments(harvestModel, scopedFilters) {
				return nil, fmt.Errorf("harvest record not found")
			}
			break
		}

		harvestModel, err = r.PanenResolver.HarvestRecordByManager(ctx, id, userID)
		if err != nil {
			var harvestErr *panenModels.HarvestError
			if errors.As(err, &harvestErr) && harvestErr.Code == panenModels.ErrHarvestNotFound {
				return nil, fmt.Errorf("harvest record not found")
			}
			return nil, err
		}
		if harvestModel == nil {
			return nil, nil
		}
	case auth.UserRoleAsisten, auth.UserRoleAreaManager, auth.UserRoleCompanyAdmin:
		scopedFilters, hasScope, scopeErr := r.buildScopedHarvestFilters(ctx, userID, role, nil)
		if scopeErr != nil {
			return nil, scopeErr
		}
		if hasScope {
			harvestModel, err = r.PanenResolver.HarvestRecord(ctx, id)
			if err != nil {
				return nil, err
			}
			if harvestModel == nil {
				return nil, nil
			}
			if !isHarvestRecordInScopedAssignments(harvestModel, scopedFilters) {
				return nil, fmt.Errorf("harvest record not found")
			}
			break
		}

		hierarchyFilters, hasHierarchyScope, hierarchyErr := r.buildHierarchyMandorScopedHarvestFilters(ctx, userID, nil)
		if hierarchyErr != nil {
			return nil, hierarchyErr
		}
		if !hasHierarchyScope {
			return nil, fmt.Errorf("harvest record not found")
		}

		harvestModel, err = r.PanenResolver.HarvestRecord(ctx, id)
		if err != nil {
			return nil, err
		}
		if harvestModel == nil {
			return nil, nil
		}
		if !isHarvestRecordInScopedAssignments(harvestModel, hierarchyFilters) {
			return nil, fmt.Errorf("harvest record not found")
		}
	default:
		harvestModel, err = r.PanenResolver.HarvestRecord(ctx, id)
		if err != nil {
			return nil, err
		}
		if harvestModel == nil {
			return nil, nil
		}
	}

	return (*mandor.HarvestRecord)(harvestModel), nil
}

// HarvestRecordsByStatus is the resolver for the harvestRecordsByStatus field.
func (r *queryResolver) HarvestRecordsByStatus(ctx context.Context, status mandor.HarvestStatus) ([]*mandor.HarvestRecord, error) {
	userID, role := getCurrentUserScope(ctx)
	if userID == "" {
		return nil, fmt.Errorf("authentication required")
	}

	var harvestModels []*panenModels.HarvestRecord

	if role == auth.UserRoleMandor {
		records, fetchErr := r.PanenResolver.HarvestRecordsByMandor(ctx, userID, &panenModels.HarvestFilters{
			Status: &status,
		})
		if fetchErr != nil {
			return nil, fetchErr
		}
		harvestModels = records
	} else if role == auth.UserRoleManager {
		filters := &panenModels.HarvestFilters{
			Status: &status,
		}
		scopedFilters, hasScope, scopeErr := r.buildScopedHarvestFilters(ctx, userID, role, filters)
		if scopeErr != nil {
			return nil, scopeErr
		}
		if hasScope {
			records, fetchErr := r.PanenResolver.HarvestRecords(ctx, scopedFilters)
			if fetchErr != nil {
				return nil, fetchErr
			}
			harvestModels = records
		} else {
			records, fetchErr := r.PanenResolver.HarvestRecordsByManagerAndStatus(ctx, userID, status)
			if fetchErr != nil {
				return nil, fetchErr
			}
			harvestModels = records
		}
	} else if role == auth.UserRoleAsisten || role == auth.UserRoleAreaManager || role == auth.UserRoleCompanyAdmin {
		filters := &panenModels.HarvestFilters{
			Status: &status,
		}
		scopedFilters, hasScope, scopeErr := r.buildScopedHarvestFilters(ctx, userID, role, filters)
		if scopeErr != nil {
			return nil, scopeErr
		}
		if hasScope {
			records, fetchErr := r.PanenResolver.HarvestRecords(ctx, scopedFilters)
			if fetchErr != nil {
				return nil, fetchErr
			}
			harvestModels = records
		} else {
			hierarchyFilters, hasHierarchyScope, hierarchyErr := r.buildHierarchyMandorScopedHarvestFilters(ctx, userID, filters)
			if hierarchyErr != nil {
				return nil, hierarchyErr
			}
			if !hasHierarchyScope {
				return []*mandor.HarvestRecord{}, nil
			}

			records, fetchErr := r.PanenResolver.HarvestRecords(ctx, hierarchyFilters)
			if fetchErr != nil {
				return nil, fetchErr
			}
			harvestModels = records
		}
	} else {
		records, fetchErr := r.PanenResolver.HarvestRecordsByStatus(ctx, status)
		if fetchErr != nil {
			return nil, fetchErr
		}
		harvestModels = records
	}

	// Convert slice of internal models to slice of generated types
	result := make([]*mandor.HarvestRecord, len(harvestModels))
	for i, model := range harvestModels {
		result[i] = (*mandor.HarvestRecord)(model)
	}

	return result, nil
}

// MandorHarvestStatusUpdate is the resolver for the mandorHarvestStatusUpdate field.
func (r *subscriptionResolver) MandorHarvestStatusUpdate(ctx context.Context) (<-chan *mandor.MandorHarvestRecord, error) {
	panic(fmt.Errorf("not implemented: MandorHarvestStatusUpdate - mandorHarvestStatusUpdate"))
}

// MandorSyncUpdate is the resolver for the mandorSyncUpdate field.
func (r *subscriptionResolver) MandorSyncUpdate(ctx context.Context, deviceID string) (<-chan *mandor.MandorSyncStatus, error) {
	panic(fmt.Errorf("not implemented: MandorSyncUpdate - mandorSyncUpdate"))
}

// HarvestRecordCreated is the resolver for the harvestRecordCreated field.
func (r *subscriptionResolver) HarvestRecordCreated(ctx context.Context) (<-chan *mandor.HarvestRecord, error) {
	return subscribeHarvestRecordCreated(ctx)
}

// HarvestRecordApproved is the resolver for the harvestRecordApproved field.
func (r *subscriptionResolver) HarvestRecordApproved(ctx context.Context) (<-chan *mandor.HarvestRecord, error) {
	return subscribeHarvestRecordApproved(ctx)
}

// HarvestRecordRejected is the resolver for the harvestRecordRejected field.
func (r *subscriptionResolver) HarvestRecordRejected(ctx context.Context) (<-chan *mandor.HarvestRecord, error) {
	return subscribeHarvestRecordRejected(ctx)
}
