package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"agrinovagraphql/server/internal/graphql/generated"
	"context"
	"fmt"
)

// CreatePerawatanRecord is the resolver for the createPerawatanRecord field.
func (r *mutationResolver) CreatePerawatanRecord(ctx context.Context, input generated.CreatePerawatanRecordInput) (*generated.PerawatanRecord, error) {
	panic(fmt.Errorf("not implemented: CreatePerawatanRecord - createPerawatanRecord"))
}

// UpdatePerawatanRecord is the resolver for the updatePerawatanRecord field.
func (r *mutationResolver) UpdatePerawatanRecord(ctx context.Context, input generated.UpdatePerawatanRecordInput) (*generated.PerawatanRecord, error) {
	panic(fmt.Errorf("not implemented: UpdatePerawatanRecord - updatePerawatanRecord"))
}

// DeletePerawatanRecord is the resolver for the deletePerawatanRecord field.
func (r *mutationResolver) DeletePerawatanRecord(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeletePerawatanRecord - deletePerawatanRecord"))
}

// CreatePupukUsage is the resolver for the createPupukUsage field.
func (r *mutationResolver) CreatePupukUsage(ctx context.Context, input generated.CreatePupukUsageInput) (*generated.PupukUsage, error) {
	panic(fmt.Errorf("not implemented: CreatePupukUsage - createPupukUsage"))
}

// CreateHerbisidaUsage is the resolver for the createHerbisidaUsage field.
func (r *mutationResolver) CreateHerbisidaUsage(ctx context.Context, input generated.CreateHerbisidaUsageInput) (*generated.HerbisidaUsage, error) {
	panic(fmt.Errorf("not implemented: CreateHerbisidaUsage - createHerbisidaUsage"))
}

// PerawatanRecords is the resolver for the perawatanRecords field.
func (r *queryResolver) PerawatanRecords(ctx context.Context) ([]*generated.PerawatanRecord, error) {
	panic(fmt.Errorf("not implemented: PerawatanRecords - perawatanRecords"))
}

// PerawatanRecord is the resolver for the perawatanRecord field.
func (r *queryResolver) PerawatanRecord(ctx context.Context, id string) (*generated.PerawatanRecord, error) {
	panic(fmt.Errorf("not implemented: PerawatanRecord - perawatanRecord"))
}

// PerawatanRecordsByType is the resolver for the perawatanRecordsByType field.
func (r *queryResolver) PerawatanRecordsByType(ctx context.Context, jenisPerawatan generated.JenisPerawatan) ([]*generated.PerawatanRecord, error) {
	panic(fmt.Errorf("not implemented: PerawatanRecordsByType - perawatanRecordsByType"))
}

// PerawatanRecordsByStatus is the resolver for the perawatanRecordsByStatus field.
func (r *queryResolver) PerawatanRecordsByStatus(ctx context.Context, status generated.StatusPerawatan) ([]*generated.PerawatanRecord, error) {
	panic(fmt.Errorf("not implemented: PerawatanRecordsByStatus - perawatanRecordsByStatus"))
}

// PupukUsageRecords is the resolver for the pupukUsageRecords field.
func (r *queryResolver) PupukUsageRecords(ctx context.Context) ([]*generated.PupukUsage, error) {
	panic(fmt.Errorf("not implemented: PupukUsageRecords - pupukUsageRecords"))
}

// HerbisidaUsageRecords is the resolver for the herbisidaUsageRecords field.
func (r *queryResolver) HerbisidaUsageRecords(ctx context.Context) ([]*generated.HerbisidaUsage, error) {
	panic(fmt.Errorf("not implemented: HerbisidaUsageRecords - herbisidaUsageRecords"))
}
