package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	authDomain "agrinovagraphql/server/internal/graphql/domain/auth"
	masterDomain "agrinovagraphql/server/internal/graphql/domain/master"
	"agrinovagraphql/server/internal/graphql/generated"
	"agrinovagraphql/server/internal/middleware"
	"context"
	"errors"
	"fmt"
	"strings"
	"time"

	"gorm.io/gorm"
)

type perawatanRecordModel struct {
	ID                 string             `gorm:"primaryKey;column:id;type:uuid;default:gen_random_uuid()"`
	BlockID            string             `gorm:"column:block_id;type:uuid"`
	Block              masterDomain.Block `gorm:"foreignKey:BlockID;references:ID"`
	JenisPerawatan     string             `gorm:"column:jenis_perawatan;type:varchar(50)"`
	TanggalPerawatan   time.Time          `gorm:"column:tanggal_perawatan"`
	PekerjaID          string             `gorm:"column:pekerja_id;type:uuid"`
	Pekerja            authDomain.User    `gorm:"foreignKey:PekerjaID;references:ID"`
	LuasArea           float64            `gorm:"column:luas_area"`
	PupukDigunakan     *string            `gorm:"column:pupuk_digunakan"`
	HerbisidaDigunakan *string            `gorm:"column:herbisida_digunakan"`
	Catatan            *string            `gorm:"column:catatan"`
	Status             string             `gorm:"column:status;type:varchar(20)"`
	CreatedAt          time.Time          `gorm:"column:created_at;autoCreateTime"`
	UpdatedAt          time.Time          `gorm:"column:updated_at;autoUpdateTime"`
	DeletedAt          gorm.DeletedAt     `gorm:"column:deleted_at;index"`
}

func (perawatanRecordModel) TableName() string {
	return "perawatan_records"
}

type perawatanMaterialUsageModel struct {
	ID                string               `gorm:"primaryKey;column:id;type:uuid;default:gen_random_uuid()"`
	PerawatanRecordID string               `gorm:"column:perawatan_record_id;type:uuid"`
	PerawatanRecord   perawatanRecordModel `gorm:"foreignKey:PerawatanRecordID;references:ID"`
	MaterialCategory  string               `gorm:"column:material_category;type:varchar(20)"`
	MaterialName      string               `gorm:"column:material_name"`
	Quantity          float64              `gorm:"column:quantity"`
	Unit              string               `gorm:"column:unit;type:varchar(20)"`
	UnitPrice         float64              `gorm:"column:unit_price"`
	TotalCost         float64              `gorm:"column:total_cost"`
	CreatedAt         time.Time            `gorm:"column:created_at;autoCreateTime"`
	UpdatedAt         time.Time            `gorm:"column:updated_at;autoUpdateTime"`
}

func (perawatanMaterialUsageModel) TableName() string {
	return "perawatan_material_usages"
}

func (r *Resolver) requireMandorPerawatan(ctx context.Context) (string, string, error) {
	userID := middleware.GetUserFromContext(ctx)
	if userID == "" {
		return "", "", fmt.Errorf("authentication required")
	}

	currentRole := middleware.GetUserRoleFromContext(ctx)
	if currentRole != "" && currentRole != authDomain.UserRoleMandor {
		return "", "", fmt.Errorf("only mandor users can access maintenance workflows")
	}

	companyID := middleware.GetCompanyFromContext(ctx)
	query := r.db.WithContext(ctx).
		Table("users").
		Joins("JOIN user_company_assignments ON user_company_assignments.user_id = users.id").
		Where("users.id = ?", userID).
		Where("users.role = ?", string(authDomain.UserRoleMandor)).
		Where("user_company_assignments.is_active = ?", true).
		Where("user_company_assignments.mandor_type = ?", string(authDomain.MandorTypePerawatan))

	if companyID != "" {
		query = query.Where("user_company_assignments.company_id = ?", companyID)
	}

	var count int64
	if err := query.Count(&count).Error; err != nil {
		return "", "", fmt.Errorf("failed to validate maintenance supervisor access: %w", err)
	}
	if count == 0 {
		return "", "", fmt.Errorf("maintenance transactions are only available for mandor perawatan")
	}

	return userID, companyID, nil
}

func (r *Resolver) basePerawatanRecordQuery(ctx context.Context, userID, companyID string) *gorm.DB {
	query := r.db.WithContext(ctx).
		Model(&perawatanRecordModel{}).
		Preload("Block").
		Preload("Pekerja").
		Where("perawatan_records.pekerja_id = ?", userID)

	if companyID != "" {
		query = query.
			Joins("JOIN blocks ON blocks.id = perawatan_records.block_id").
			Joins("JOIN divisions ON divisions.id = blocks.division_id").
			Joins("JOIN estates ON estates.id = divisions.estate_id").
			Where("estates.company_id = ?", companyID)
	}

	return query
}

func (r *Resolver) getPerawatanRecordByID(ctx context.Context, id, userID, companyID string) (*perawatanRecordModel, error) {
	var record perawatanRecordModel
	err := r.basePerawatanRecordQuery(ctx, userID, companyID).
		Where("perawatan_records.id = ?", id).
		First(&record).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, nil
		}
		return nil, fmt.Errorf("failed to load maintenance record: %w", err)
	}

	return &record, nil
}

func (r *Resolver) loadPerawatanBlock(ctx context.Context, blockID, companyID string) (*masterDomain.Block, error) {
	query := r.db.WithContext(ctx).
		Model(&masterDomain.Block{}).
		Joins("JOIN divisions ON divisions.id = blocks.division_id").
		Joins("JOIN estates ON estates.id = divisions.estate_id").
		Where("blocks.id = ?", blockID)

	if companyID != "" {
		query = query.Where("estates.company_id = ?", companyID)
	}

	var block masterDomain.Block
	if err := query.First(&block).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, fmt.Errorf("block not found")
		}
		return nil, fmt.Errorf("failed to load block: %w", err)
	}

	return &block, nil
}

func mapPerawatanRecordModel(record *perawatanRecordModel) *generated.PerawatanRecord {
	if record == nil {
		return nil
	}

	block := record.Block
	pekerja := record.Pekerja

	return &generated.PerawatanRecord{
		ID:                 record.ID,
		BlockID:            record.BlockID,
		Block:              &block,
		JenisPerawatan:     generated.JenisPerawatan(record.JenisPerawatan),
		TanggalPerawatan:   record.TanggalPerawatan,
		PekerjaID:          record.PekerjaID,
		Pekerja:            &pekerja,
		LuasArea:           record.LuasArea,
		PupukDigunakan:     record.PupukDigunakan,
		HerbisidaDigunakan: record.HerbisidaDigunakan,
		Catatan:            record.Catatan,
		Status:             generated.StatusPerawatan(record.Status),
		CreatedAt:          record.CreatedAt,
		UpdatedAt:          record.UpdatedAt,
	}
}

func mapPerawatanRecordModels(records []perawatanRecordModel) []*generated.PerawatanRecord {
	result := make([]*generated.PerawatanRecord, 0, len(records))
	for i := range records {
		result = append(result, mapPerawatanRecordModel(&records[i]))
	}
	return result
}

func (r *Resolver) basePerawatanMaterialUsageQuery(ctx context.Context, userID, companyID string) *gorm.DB {
	query := r.db.WithContext(ctx).
		Model(&perawatanMaterialUsageModel{}).
		Preload("PerawatanRecord").
		Preload("PerawatanRecord.Block").
		Preload("PerawatanRecord.Pekerja").
		Joins("JOIN perawatan_records ON perawatan_records.id = perawatan_material_usages.perawatan_record_id").
		Where("perawatan_records.pekerja_id = ?", userID).
		Where("perawatan_records.deleted_at IS NULL")

	if companyID != "" {
		query = query.
			Joins("JOIN blocks ON blocks.id = perawatan_records.block_id").
			Joins("JOIN divisions ON divisions.id = blocks.division_id").
			Joins("JOIN estates ON estates.id = divisions.estate_id").
			Where("estates.company_id = ?", companyID)
	}

	return query
}

func (r *Resolver) getPerawatanMaterialUsageByID(ctx context.Context, id, userID, companyID string) (*perawatanMaterialUsageModel, error) {
	var usage perawatanMaterialUsageModel
	err := r.basePerawatanMaterialUsageQuery(ctx, userID, companyID).
		Where("perawatan_material_usages.id = ?", id).
		First(&usage).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, nil
		}
		return nil, fmt.Errorf("failed to load maintenance material usage: %w", err)
	}

	return &usage, nil
}

func validatePerawatanMaterialCategoryUnit(category generated.PerawatanMaterialCategory, unit generated.PerawatanMaterialUnit) error {
	switch category {
	case generated.PerawatanMaterialCategoryPupuk:
		if unit != generated.PerawatanMaterialUnitKg {
			return fmt.Errorf("materialCategory PUPUK must use unit KG")
		}
	case generated.PerawatanMaterialCategoryHerbisida:
		if unit != generated.PerawatanMaterialUnitLiter {
			return fmt.Errorf("materialCategory HERBISIDA must use unit LITER")
		}
	default:
		return fmt.Errorf("invalid materialCategory")
	}

	return nil
}

func mapPerawatanMaterialUsageModel(usage *perawatanMaterialUsageModel) *generated.PerawatanMaterialUsage {
	if usage == nil {
		return nil
	}

	return &generated.PerawatanMaterialUsage{
		ID:                usage.ID,
		PerawatanRecordID: usage.PerawatanRecordID,
		PerawatanRecord:   mapPerawatanRecordModel(&usage.PerawatanRecord),
		MaterialCategory:  generated.PerawatanMaterialCategory(usage.MaterialCategory),
		MaterialName:      usage.MaterialName,
		Quantity:          usage.Quantity,
		Unit:              generated.PerawatanMaterialUnit(usage.Unit),
		UnitPrice:         usage.UnitPrice,
		TotalCost:         usage.TotalCost,
		CreatedAt:         usage.CreatedAt,
		UpdatedAt:         usage.UpdatedAt,
	}
}

func mapPerawatanMaterialUsageModels(usages []perawatanMaterialUsageModel) []*generated.PerawatanMaterialUsage {
	result := make([]*generated.PerawatanMaterialUsage, 0, len(usages))
	for i := range usages {
		result = append(result, mapPerawatanMaterialUsageModel(&usages[i]))
	}
	return result
}

// CreatePerawatanRecord is the resolver for the createPerawatanRecord field.
func (r *mutationResolver) CreatePerawatanRecord(ctx context.Context, input generated.CreatePerawatanRecordInput) (*generated.PerawatanRecord, error) {
	userID, companyID, err := r.requireMandorPerawatan(ctx)
	if err != nil {
		return nil, err
	}
	if input.PekerjaID != userID {
		return nil, fmt.Errorf("pekerjaId must match the authenticated mandor")
	}
	if input.LuasArea <= 0 {
		return nil, fmt.Errorf("luasArea must be greater than 0")
	}
	if input.TanggalPerawatan.IsZero() {
		return nil, fmt.Errorf("tanggalPerawatan is required")
	}

	if _, err := r.loadPerawatanBlock(ctx, input.BlockID, companyID); err != nil {
		return nil, err
	}

	record := perawatanRecordModel{
		BlockID:            input.BlockID,
		JenisPerawatan:     string(input.JenisPerawatan),
		TanggalPerawatan:   input.TanggalPerawatan,
		PekerjaID:          userID,
		LuasArea:           input.LuasArea,
		PupukDigunakan:     input.PupukDigunakan,
		HerbisidaDigunakan: input.HerbisidaDigunakan,
		Catatan:            input.Catatan,
		Status:             string(generated.StatusPerawatanPlanned),
	}

	if err := r.db.WithContext(ctx).Create(&record).Error; err != nil {
		return nil, fmt.Errorf("failed to create maintenance record: %w", err)
	}

	createdRecord, err := r.getPerawatanRecordByID(ctx, record.ID, userID, companyID)
	if err != nil {
		return nil, err
	}
	if createdRecord == nil {
		return nil, fmt.Errorf("maintenance record created but could not be reloaded")
	}

	return mapPerawatanRecordModel(createdRecord), nil
}

// UpdatePerawatanRecord is the resolver for the updatePerawatanRecord field.
func (r *mutationResolver) UpdatePerawatanRecord(ctx context.Context, input generated.UpdatePerawatanRecordInput) (*generated.PerawatanRecord, error) {
	userID, companyID, err := r.requireMandorPerawatan(ctx)
	if err != nil {
		return nil, err
	}

	record, err := r.getPerawatanRecordByID(ctx, input.ID, userID, companyID)
	if err != nil {
		return nil, err
	}
	if record == nil {
		return nil, fmt.Errorf("maintenance record not found")
	}

	if input.LuasArea != nil && *input.LuasArea <= 0 {
		return nil, fmt.Errorf("luasArea must be greater than 0")
	}

	updates := map[string]any{
		"updated_at": time.Now(),
	}
	if input.JenisPerawatan != nil {
		updates["jenis_perawatan"] = string(*input.JenisPerawatan)
	}
	if input.TanggalPerawatan != nil {
		if input.TanggalPerawatan.IsZero() {
			return nil, fmt.Errorf("tanggalPerawatan must not be empty")
		}
		updates["tanggal_perawatan"] = *input.TanggalPerawatan
	}
	if input.LuasArea != nil {
		updates["luas_area"] = *input.LuasArea
	}
	if input.PupukDigunakan != nil {
		updates["pupuk_digunakan"] = *input.PupukDigunakan
	}
	if input.HerbisidaDigunakan != nil {
		updates["herbisida_digunakan"] = *input.HerbisidaDigunakan
	}
	if input.Catatan != nil {
		updates["catatan"] = *input.Catatan
	}
	if input.Status != nil {
		updates["status"] = string(*input.Status)
	}

	if err := r.db.WithContext(ctx).
		Model(&perawatanRecordModel{}).
		Where("id = ?", record.ID).
		Updates(updates).Error; err != nil {
		return nil, fmt.Errorf("failed to update maintenance record: %w", err)
	}

	updatedRecord, err := r.getPerawatanRecordByID(ctx, record.ID, userID, companyID)
	if err != nil {
		return nil, err
	}
	if updatedRecord == nil {
		return nil, fmt.Errorf("maintenance record not found after update")
	}

	return mapPerawatanRecordModel(updatedRecord), nil
}

// DeletePerawatanRecord is the resolver for the deletePerawatanRecord field.
func (r *mutationResolver) DeletePerawatanRecord(ctx context.Context, id string) (bool, error) {
	userID, companyID, err := r.requireMandorPerawatan(ctx)
	if err != nil {
		return false, err
	}

	record, err := r.getPerawatanRecordByID(ctx, id, userID, companyID)
	if err != nil {
		return false, err
	}
	if record == nil {
		return false, fmt.Errorf("maintenance record not found")
	}

	if err := r.db.WithContext(ctx).Delete(record).Error; err != nil {
		return false, fmt.Errorf("failed to delete maintenance record: %w", err)
	}

	return true, nil
}

// CreatePerawatanMaterialUsage is the resolver for the createPerawatanMaterialUsage field.
func (r *mutationResolver) CreatePerawatanMaterialUsage(ctx context.Context, input generated.CreatePerawatanMaterialUsageInput) (*generated.PerawatanMaterialUsage, error) {
	userID, companyID, err := r.requireMandorPerawatan(ctx)
	if err != nil {
		return nil, err
	}

	record, err := r.getPerawatanRecordByID(ctx, input.PerawatanRecordID, userID, companyID)
	if err != nil {
		return nil, err
	}
	if record == nil {
		return nil, fmt.Errorf("maintenance record not found")
	}
	if strings.TrimSpace(input.MaterialName) == "" {
		return nil, fmt.Errorf("materialName is required")
	}
	if input.Quantity <= 0 {
		return nil, fmt.Errorf("quantity must be greater than 0")
	}
	if input.UnitPrice < 0 {
		return nil, fmt.Errorf("unitPrice must not be negative")
	}
	if err := validatePerawatanMaterialCategoryUnit(input.MaterialCategory, input.Unit); err != nil {
		return nil, err
	}

	usage := perawatanMaterialUsageModel{
		PerawatanRecordID: input.PerawatanRecordID,
		MaterialCategory:  string(input.MaterialCategory),
		MaterialName:      strings.TrimSpace(input.MaterialName),
		Quantity:          input.Quantity,
		Unit:              string(input.Unit),
		UnitPrice:         input.UnitPrice,
		TotalCost:         input.Quantity * input.UnitPrice,
	}

	if err := r.db.WithContext(ctx).Create(&usage).Error; err != nil {
		return nil, fmt.Errorf("failed to create maintenance material usage: %w", err)
	}

	createdUsage, err := r.getPerawatanMaterialUsageByID(ctx, usage.ID, userID, companyID)
	if err != nil {
		return nil, err
	}
	if createdUsage == nil {
		return nil, fmt.Errorf("maintenance material usage created but could not be reloaded")
	}

	return mapPerawatanMaterialUsageModel(createdUsage), nil
}

// UpdatePerawatanMaterialUsage is the resolver for the updatePerawatanMaterialUsage field.
func (r *mutationResolver) UpdatePerawatanMaterialUsage(ctx context.Context, input generated.UpdatePerawatanMaterialUsageInput) (*generated.PerawatanMaterialUsage, error) {
	userID, companyID, err := r.requireMandorPerawatan(ctx)
	if err != nil {
		return nil, err
	}

	usage, err := r.getPerawatanMaterialUsageByID(ctx, input.ID, userID, companyID)
	if err != nil {
		return nil, err
	}
	if usage == nil {
		return nil, fmt.Errorf("maintenance material usage not found")
	}

	if input.MaterialName != nil && strings.TrimSpace(*input.MaterialName) == "" {
		return nil, fmt.Errorf("materialName must not be empty")
	}
	if input.Quantity != nil && *input.Quantity <= 0 {
		return nil, fmt.Errorf("quantity must be greater than 0")
	}
	if input.UnitPrice != nil && *input.UnitPrice < 0 {
		return nil, fmt.Errorf("unitPrice must not be negative")
	}

	category := generated.PerawatanMaterialCategory(usage.MaterialCategory)
	if input.MaterialCategory != nil {
		category = *input.MaterialCategory
	}

	unit := generated.PerawatanMaterialUnit(usage.Unit)
	if input.Unit != nil {
		unit = *input.Unit
	}

	if err := validatePerawatanMaterialCategoryUnit(category, unit); err != nil {
		return nil, err
	}

	quantity := usage.Quantity
	if input.Quantity != nil {
		quantity = *input.Quantity
	}

	unitPrice := usage.UnitPrice
	if input.UnitPrice != nil {
		unitPrice = *input.UnitPrice
	}

	updates := map[string]any{
		"updated_at":        time.Now(),
		"material_category": string(category),
		"unit":              string(unit),
		"total_cost":        quantity * unitPrice,
	}
	if input.MaterialName != nil {
		updates["material_name"] = strings.TrimSpace(*input.MaterialName)
	}
	if input.Quantity != nil {
		updates["quantity"] = quantity
	}
	if input.UnitPrice != nil {
		updates["unit_price"] = unitPrice
	}

	if err := r.db.WithContext(ctx).
		Model(&perawatanMaterialUsageModel{}).
		Where("id = ?", usage.ID).
		Updates(updates).Error; err != nil {
		return nil, fmt.Errorf("failed to update maintenance material usage: %w", err)
	}

	updatedUsage, err := r.getPerawatanMaterialUsageByID(ctx, usage.ID, userID, companyID)
	if err != nil {
		return nil, err
	}
	if updatedUsage == nil {
		return nil, fmt.Errorf("maintenance material usage not found after update")
	}

	return mapPerawatanMaterialUsageModel(updatedUsage), nil
}

// DeletePerawatanMaterialUsage is the resolver for the deletePerawatanMaterialUsage field.
func (r *mutationResolver) DeletePerawatanMaterialUsage(ctx context.Context, id string) (bool, error) {
	userID, companyID, err := r.requireMandorPerawatan(ctx)
	if err != nil {
		return false, err
	}

	usage, err := r.getPerawatanMaterialUsageByID(ctx, id, userID, companyID)
	if err != nil {
		return false, err
	}
	if usage == nil {
		return false, fmt.Errorf("maintenance material usage not found")
	}

	if err := r.db.WithContext(ctx).Delete(usage).Error; err != nil {
		return false, fmt.Errorf("failed to delete maintenance material usage: %w", err)
	}

	return true, nil
}

// PerawatanRecords is the resolver for the perawatanRecords field.
func (r *queryResolver) PerawatanRecords(ctx context.Context) ([]*generated.PerawatanRecord, error) {
	userID, companyID, err := r.requireMandorPerawatan(ctx)
	if err != nil {
		return nil, err
	}

	var records []perawatanRecordModel
	if err := r.basePerawatanRecordQuery(ctx, userID, companyID).
		Order("perawatan_records.tanggal_perawatan DESC").
		Order("perawatan_records.created_at DESC").
		Find(&records).Error; err != nil {
		return nil, fmt.Errorf("failed to load maintenance records: %w", err)
	}

	return mapPerawatanRecordModels(records), nil
}

// PerawatanRecord is the resolver for the perawatanRecord field.
func (r *queryResolver) PerawatanRecord(ctx context.Context, id string) (*generated.PerawatanRecord, error) {
	userID, companyID, err := r.requireMandorPerawatan(ctx)
	if err != nil {
		return nil, err
	}

	record, err := r.getPerawatanRecordByID(ctx, id, userID, companyID)
	if err != nil {
		return nil, err
	}
	if record == nil {
		return nil, nil
	}

	return mapPerawatanRecordModel(record), nil
}

// PerawatanRecordsByType is the resolver for the perawatanRecordsByType field.
func (r *queryResolver) PerawatanRecordsByType(ctx context.Context, jenisPerawatan generated.JenisPerawatan) ([]*generated.PerawatanRecord, error) {
	userID, companyID, err := r.requireMandorPerawatan(ctx)
	if err != nil {
		return nil, err
	}

	var records []perawatanRecordModel
	if err := r.basePerawatanRecordQuery(ctx, userID, companyID).
		Where("perawatan_records.jenis_perawatan = ?", string(jenisPerawatan)).
		Order("perawatan_records.tanggal_perawatan DESC").
		Order("perawatan_records.created_at DESC").
		Find(&records).Error; err != nil {
		return nil, fmt.Errorf("failed to load maintenance records by type: %w", err)
	}

	return mapPerawatanRecordModels(records), nil
}

// PerawatanRecordsByStatus is the resolver for the perawatanRecordsByStatus field.
func (r *queryResolver) PerawatanRecordsByStatus(ctx context.Context, status generated.StatusPerawatan) ([]*generated.PerawatanRecord, error) {
	userID, companyID, err := r.requireMandorPerawatan(ctx)
	if err != nil {
		return nil, err
	}

	var records []perawatanRecordModel
	if err := r.basePerawatanRecordQuery(ctx, userID, companyID).
		Where("perawatan_records.status = ?", string(status)).
		Order("perawatan_records.tanggal_perawatan DESC").
		Order("perawatan_records.created_at DESC").
		Find(&records).Error; err != nil {
		return nil, fmt.Errorf("failed to load maintenance records by status: %w", err)
	}

	return mapPerawatanRecordModels(records), nil
}

// PerawatanMaterialUsageRecords is the resolver for the perawatanMaterialUsageRecords field.
func (r *queryResolver) PerawatanMaterialUsageRecords(ctx context.Context) ([]*generated.PerawatanMaterialUsage, error) {
	userID, companyID, err := r.requireMandorPerawatan(ctx)
	if err != nil {
		return nil, err
	}

	var usages []perawatanMaterialUsageModel
	if err := r.basePerawatanMaterialUsageQuery(ctx, userID, companyID).
		Order("perawatan_material_usages.created_at DESC").
		Find(&usages).Error; err != nil {
		return nil, fmt.Errorf("failed to load maintenance material usage records: %w", err)
	}

	return mapPerawatanMaterialUsageModels(usages), nil
}

// PerawatanMaterialUsageRecord is the resolver for the perawatanMaterialUsageRecord field.
func (r *queryResolver) PerawatanMaterialUsageRecord(ctx context.Context, id string) (*generated.PerawatanMaterialUsage, error) {
	userID, companyID, err := r.requireMandorPerawatan(ctx)
	if err != nil {
		return nil, err
	}

	usage, err := r.getPerawatanMaterialUsageByID(ctx, id, userID, companyID)
	if err != nil {
		return nil, err
	}
	if usage == nil {
		return nil, nil
	}

	return mapPerawatanMaterialUsageModel(usage), nil
}

// PerawatanMaterialUsageRecordsByCategory is the resolver for the perawatanMaterialUsageRecordsByCategory field.
func (r *queryResolver) PerawatanMaterialUsageRecordsByCategory(ctx context.Context, materialCategory generated.PerawatanMaterialCategory) ([]*generated.PerawatanMaterialUsage, error) {
	userID, companyID, err := r.requireMandorPerawatan(ctx)
	if err != nil {
		return nil, err
	}

	var usages []perawatanMaterialUsageModel
	if err := r.basePerawatanMaterialUsageQuery(ctx, userID, companyID).
		Where("perawatan_material_usages.material_category = ?", string(materialCategory)).
		Order("perawatan_material_usages.created_at DESC").
		Find(&usages).Error; err != nil {
		return nil, fmt.Errorf("failed to load maintenance material usage records by category: %w", err)
	}

	return mapPerawatanMaterialUsageModels(usages), nil
}

// PerawatanMaterialUsageRecordsByRecord is the resolver for the perawatanMaterialUsageRecordsByRecord field.
func (r *queryResolver) PerawatanMaterialUsageRecordsByRecord(ctx context.Context, perawatanRecordID string) ([]*generated.PerawatanMaterialUsage, error) {
	userID, companyID, err := r.requireMandorPerawatan(ctx)
	if err != nil {
		return nil, err
	}

	record, err := r.getPerawatanRecordByID(ctx, perawatanRecordID, userID, companyID)
	if err != nil {
		return nil, err
	}
	if record == nil {
		return nil, fmt.Errorf("maintenance record not found")
	}

	var usages []perawatanMaterialUsageModel
	if err := r.basePerawatanMaterialUsageQuery(ctx, userID, companyID).
		Where("perawatan_material_usages.perawatan_record_id = ?", perawatanRecordID).
		Order("perawatan_material_usages.created_at DESC").
		Find(&usages).Error; err != nil {
		return nil, fmt.Errorf("failed to load maintenance material usage records by record: %w", err)
	}

	return mapPerawatanMaterialUsageModels(usages), nil
}
