package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"agrinovagraphql/server/internal/graphql/generated"
	"context"
	"fmt"
)

// CreatePKSRecord is the resolver for the createPKSRecord field.
func (r *mutationResolver) CreatePKSRecord(ctx context.Context, input generated.CreatePKSRecordInput) (*generated.PKSRecord, error) {
	panic(fmt.Errorf("not implemented: CreatePKSRecord - createPKSRecord"))
}

// UpdatePKSRecord is the resolver for the updatePKSRecord field.
func (r *mutationResolver) UpdatePKSRecord(ctx context.Context, input generated.UpdatePKSRecordInput) (*generated.PKSRecord, error) {
	panic(fmt.Errorf("not implemented: UpdatePKSRecord - updatePKSRecord"))
}

// DeletePKSRecord is the resolver for the deletePKSRecord field.
func (r *mutationResolver) DeletePKSRecord(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeletePKSRecord - deletePKSRecord"))
}

// CalculateBjr is the resolver for the calculateBJR field.
func (r *mutationResolver) CalculateBjr(ctx context.Context, pksRecordID string) (*generated.BJRCalculation, error) {
	panic(fmt.Errorf("not implemented: CalculateBjr - calculateBJR"))
}

// PksRecords is the resolver for the pksRecords field.
func (r *queryResolver) PksRecords(ctx context.Context) ([]*generated.PKSRecord, error) {
	panic(fmt.Errorf("not implemented: PksRecords - pksRecords"))
}

// PksRecord is the resolver for the pksRecord field.
func (r *queryResolver) PksRecord(ctx context.Context, id string) (*generated.PKSRecord, error) {
	panic(fmt.Errorf("not implemented: PksRecord - pksRecord"))
}

// PksRecordsByQuality is the resolver for the pksRecordsByQuality field.
func (r *queryResolver) PksRecordsByQuality(ctx context.Context, kualitas generated.PKSKualitas) ([]*generated.PKSRecord, error) {
	panic(fmt.Errorf("not implemented: PksRecordsByQuality - pksRecordsByQuality"))
}

// BjrCalculations is the resolver for the bjrCalculations field.
func (r *queryResolver) BjrCalculations(ctx context.Context) ([]*generated.BJRCalculation, error) {
	panic(fmt.Errorf("not implemented: BjrCalculations - bjrCalculations"))
}

// BjrCalculationByPks is the resolver for the bjrCalculationByPKS field.
func (r *queryResolver) BjrCalculationByPks(ctx context.Context, pksRecordID string) (*generated.BJRCalculation, error) {
	panic(fmt.Errorf("not implemented: BjrCalculationByPks - bjrCalculationByPKS"))
}
