package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"agrinovagraphql/server/internal/auth/services"
	auth "agrinovagraphql/server/internal/graphql/domain/auth"
	mandor "agrinovagraphql/server/internal/graphql/domain/mandor"
	"agrinovagraphql/server/internal/graphql/generated"
	"agrinovagraphql/server/internal/notifications/models"
	"context"
	"fmt"
)

// Role Hierarchy Resolvers

func (r *queryResolver) RoleInfo(ctx context.Context, role auth.UserRole) (*generated.RoleInfo, error) {
	info, err := r.RoleHierarchyService.GetRoleInfo(role)
	if err != nil {
		return nil, err
	}

	return &generated.RoleInfo{
		Role:         info.Role,
		Level:        int32(info.Level),
		Name:         info.Name,
		Description:  info.Description,
		Permissions:  info.Permissions,
		WebAccess:    info.WebAccess,
		MobileAccess: info.MobileAccess,
	}, nil
}

func (r *queryResolver) AllRoles(ctx context.Context) ([]*generated.RoleInfo, error) {
	roles := r.RoleHierarchyService.GetAllRoles()
	result := make([]*generated.RoleInfo, len(roles))

	for i, role := range roles {
		result[i] = &generated.RoleInfo{
			Role:         role.Role,
			Level:        int32(role.Level),
			Name:         role.Name,
			Description:  role.Description,
			Permissions:  role.Permissions,
			WebAccess:    role.WebAccess,
			MobileAccess: role.MobileAccess,
		}
	}

	return result, nil
}

func (r *queryResolver) RoleHierarchyTree(ctx context.Context) ([]*generated.RoleHierarchyTree, error) {
	tree := r.RoleHierarchyService.GetRoleHierarchyTree()
	var result []*generated.RoleHierarchyTree

	// Sort by level
	for level := services.RoleLevel(1); level <= services.LevelGrading; level++ {
		if roles, exists := tree[level]; exists {
			treeLevel := &generated.RoleHierarchyTree{
				Level: int32(level),
				Roles: make([]*generated.RoleInfo, len(roles)),
			}

			for i, role := range roles {
				treeLevel.Roles[i] = &generated.RoleInfo{
					Role:         role.Role,
					Level:        int32(role.Level),
					Name:         role.Name,
					Description:  role.Description,
					Permissions:  role.Permissions,
					WebAccess:    role.WebAccess,
					MobileAccess: role.MobileAccess,
				}
			}

			result = append(result, treeLevel)
		}
	}

	return result, nil
}

func (r *queryResolver) CheckRoleAccess(ctx context.Context, requesterRole auth.UserRole, targetRole auth.UserRole) (*generated.RoleAccessCheck, error) {
	canAccess := r.RoleHierarchyService.CanAccess(requesterRole, targetRole)
	canManage := r.RoleHierarchyService.CanManage(requesterRole, targetRole)
	canAssignRole := r.RoleHierarchyService.CanAssignRole(requesterRole, targetRole)

	// Generate explanation
	var explanation string
	if canAccess {
		if requesterRole == targetRole {
			explanation = "Same role - access granted"
		} else if requesterLevel, _ := r.RoleHierarchyService.GetRoleLevel(requesterRole); requesterLevel == services.LevelSuperAdmin {
			explanation = "Super admin has access to all roles"
		} else {
			explanation = "Higher hierarchy level grants access to lower levels"
		}
	} else {
		explanation = "Insufficient hierarchy level for access"
	}

	return &generated.RoleAccessCheck{
		CanAccess:     canAccess,
		CanManage:     canManage,
		CanAssignRole: canAssignRole,
		RequesterRole: requesterRole,
		TargetRole:    targetRole,
		Explanation:   &explanation,
	}, nil
}

func (r *queryResolver) CheckRolePermission(ctx context.Context, role auth.UserRole, permission string) (*generated.RolePermissionCheck, error) {
	hasPermission := r.RoleHierarchyService.HasPermission(role, permission)

	var reason *string
	if hasPermission {
		reasonText := "Role has explicit permission or wildcard access"
		reason = &reasonText
	} else {
		reasonText := "Role does not have this permission"
		reason = &reasonText
	}

	return &generated.RolePermissionCheck{
		HasPermission: hasPermission,
		Permission:    permission,
		Reason:        reason,
	}, nil
}

func (r *queryResolver) GetAccessibleRoles(ctx context.Context, requesterRole auth.UserRole) ([]auth.UserRole, error) {
	return r.RoleHierarchyService.GetAccessibleRoles(requesterRole), nil
}

func (r *queryResolver) GetManageableRoles(ctx context.Context, requesterRole auth.UserRole) ([]auth.UserRole, error) {
	return r.RoleHierarchyService.GetManageableRoles(requesterRole), nil
}

func (r *queryResolver) GetAssignableRoles(ctx context.Context, requesterRole auth.UserRole) ([]auth.UserRole, error) {
	return r.RoleHierarchyService.GetAssignableRoles(requesterRole), nil
}

func (r *queryResolver) GetHierarchicalSuperiors(ctx context.Context, role auth.UserRole) ([]auth.UserRole, error) {
	return r.RoleHierarchyService.GetHierarchicalSuperiors(role), nil
}

func (r *queryResolver) GetHierarchicalSubordinates(ctx context.Context, role auth.UserRole) ([]auth.UserRole, error) {
	return r.RoleHierarchyService.GetHierarchicalSubordinates(role), nil
}

// NotificationSummary returns notification summary for the current user
func (r *queryResolver) NotificationSummary(ctx context.Context) (*models.NotificationSummary, error) {
	// Get current user ID from context
	userID, err := r.getUserIDFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("authentication required: %w", err)
	}

	// Get summary
	summary, err := r.NotificationService.GetNotificationSummary(ctx, userID)
	if err != nil {
		return nil, fmt.Errorf("failed to get notification summary: %w", err)
	}

	return summary, nil
}

// Field resolvers (return nil for now - gqlgen will auto-generate needed resolvers)

// Block returns generated.BlockResolver implementation.
func (r *Resolver) Block() generated.BlockResolver { return &blockResolver{r} }

// Company returns generated.CompanyResolver implementation.
func (r *Resolver) Company() generated.CompanyResolver { return nil }

// GradingRecord returns generated.GradingRecordResolver implementation.
func (r *Resolver) GradingRecord() generated.GradingRecordResolver { return nil }

// MandorPendingSyncItem returns generated.MandorPendingSyncItemResolver implementation.
func (r *Resolver) MandorPendingSyncItem() generated.MandorPendingSyncItemResolver { return nil }

// MandorPhotoSyncResult returns generated.MandorPhotoSyncResultResolver implementation.
func (r *Resolver) MandorPhotoSyncResult() generated.MandorPhotoSyncResultResolver { return nil }

// SatpamGuestLog returns generated.SatpamGuestLogResolver implementation.
func (r *Resolver) SatpamGuestLog() generated.SatpamGuestLogResolver {
	return &satpamGuestLogResolver{r}
}

// SatpamSyncResult returns generated.SatpamSyncResultResolver implementation.
func (r *Resolver) SatpamSyncResult() generated.SatpamSyncResultResolver {
	return &satpamSyncResultResolver{r}
}

// ShiftInfo returns generated.ShiftInfoResolver implementation.
func (r *Resolver) ShiftInfo() generated.ShiftInfoResolver { return &shiftInfoResolver{r} }

// TeamMemberPerformance returns generated.TeamMemberPerformanceResolver implementation.
func (r *Resolver) TeamMemberPerformance() generated.TeamMemberPerformanceResolver {
	return &teamMemberPerformanceResolver{r}
}

// TimbanganDashboardData returns generated.TimbanganDashboardDataResolver implementation.
func (r *Resolver) TimbanganDashboardData() generated.TimbanganDashboardDataResolver { return nil }

// TimbanganDashboardStats returns generated.TimbanganDashboardStatsResolver implementation.
func (r *Resolver) TimbanganDashboardStats() generated.TimbanganDashboardStatsResolver { return nil }

// TrendDataPoint returns generated.TrendDataPointResolver implementation.
func (r *Resolver) TrendDataPoint() generated.TrendDataPointResolver {
	return &trendDataPointResolver{r}
}

// UserAssignmentSummary returns generated.UserAssignmentSummaryResolver implementation.
func (r *Resolver) UserAssignmentSummary() generated.UserAssignmentSummaryResolver { return nil }

// UserFeature returns generated.UserFeatureResolver implementation.
func (r *Resolver) UserFeature() generated.UserFeatureResolver { return nil }

// UserMutationResponse returns generated.UserMutationResponseResolver implementation.
func (r *Resolver) UserMutationResponse() generated.UserMutationResponseResolver { return nil }

// VehicleCompletedInfo returns generated.VehicleCompletedInfoResolver implementation.
func (r *Resolver) VehicleCompletedInfo() generated.VehicleCompletedInfoResolver {
	return &vehicleCompletedInfoResolver{r}
}

// VehicleInsideInfo returns generated.VehicleInsideInfoResolver implementation.
func (r *Resolver) VehicleInsideInfo() generated.VehicleInsideInfoResolver {
	return &vehicleInsideInfoResolver{r}
}

// VehicleOutsideInfo returns generated.VehicleOutsideInfoResolver implementation.
func (r *Resolver) VehicleOutsideInfo() generated.VehicleOutsideInfoResolver {
	return &vehicleOutsideInfoResolver{r}
}

// WeighingQueueItem returns generated.WeighingQueueItemResolver implementation.
func (r *Resolver) WeighingQueueItem() generated.WeighingQueueItemResolver { return nil }

// WeighingResult returns generated.WeighingResultResolver implementation.
func (r *Resolver) WeighingResult() generated.WeighingResultResolver { return nil }

// HarvestRecordSyncInput returns generated.HarvestRecordSyncInputResolver implementation.
func (r *Resolver) HarvestRecordSyncInput() generated.HarvestRecordSyncInputResolver {
	return &harvestRecordSyncInputResolver{r}
}

// MandorPhotoSyncInput returns generated.MandorPhotoSyncInputResolver implementation.
func (r *Resolver) MandorPhotoSyncInput() generated.MandorPhotoSyncInputResolver { return nil }

// SatpamSyncInput returns generated.SatpamSyncInputResolver implementation.
func (r *Resolver) SatpamSyncInput() generated.SatpamSyncInputResolver { return nil }

// UpdateMandorHarvestInput returns generated.UpdateMandorHarvestInputResolver implementation.
func (r *Resolver) UpdateMandorHarvestInput() generated.UpdateMandorHarvestInputResolver {
	return nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }

type harvestRecordSyncInputResolver struct{ *Resolver }

func (r *harvestRecordSyncInputResolver) Status(
	_ context.Context,
	obj *mandor.HarvestRecordSyncInput,
	data mandor.HarvestStatus,
) error {
	status := string(data)
	obj.Status = &status
	return nil
}
