package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"agrinovagraphql/server/internal/graphql/domain/timbangan"
	"agrinovagraphql/server/internal/graphql/generated"
	weighingModels "agrinovagraphql/server/internal/weighing/models"
	"context"
	"fmt"
	"time"
)

// AddToWeighingQueue is the resolver for the addToWeighingQueue field.
func (r *mutationResolver) AddToWeighingQueue(ctx context.Context, vehiclePlate string, driverName string, sourceEstate string, sourceDivision *string, doNumber *string, estimatedWeight *float64, priority *timbangan.QueuePriority) (*timbangan.WeighingQueueItem, error) {
	panic(fmt.Errorf("not implemented: AddToWeighingQueue - addToWeighingQueue"))
}

// PerformFirstWeighing is the resolver for the performFirstWeighing field.
func (r *mutationResolver) PerformFirstWeighing(ctx context.Context, input timbangan.PerformFirstWeighingInput) (*timbangan.WeighingResult, error) {
	panic(fmt.Errorf("not implemented: PerformFirstWeighing - performFirstWeighing"))
}

// PerformSecondWeighing is the resolver for the performSecondWeighing field.
func (r *mutationResolver) PerformSecondWeighing(ctx context.Context, input timbangan.PerformSecondWeighingInput) (*timbangan.WeighingResult, error) {
	panic(fmt.Errorf("not implemented: PerformSecondWeighing - performSecondWeighing"))
}

// CancelWeighing is the resolver for the cancelWeighing field.
func (r *mutationResolver) CancelWeighing(ctx context.Context, id string, reason string) (*timbangan.WeighingResult, error) {
	panic(fmt.Errorf("not implemented: CancelWeighing - cancelWeighing"))
}

// RequestReweighing is the resolver for the requestReweighing field.
func (r *mutationResolver) RequestReweighing(ctx context.Context, id string, reason string) (*timbangan.WeighingResult, error) {
	panic(fmt.Errorf("not implemented: RequestReweighing - requestReweighing"))
}

// TimbanganDashboard is the resolver for the timbanganDashboard field.
func (r *queryResolver) TimbanganDashboard(ctx context.Context) (*timbangan.TimbanganDashboardData, error) {
	panic(fmt.Errorf("not implemented: TimbanganDashboard - timbanganDashboard"))
}

// WeighingQueue is the resolver for the weighingQueue field.
func (r *queryResolver) WeighingQueue(ctx context.Context, queueType *generated.WeighingQueueType) ([]*timbangan.WeighingQueueItem, error) {
	panic(fmt.Errorf("not implemented: WeighingQueue - weighingQueue"))
}

// WeighingRecord is the resolver for the weighingRecord field.
func (r *queryResolver) WeighingRecord(ctx context.Context, id string) (*timbangan.WeighingRecord, error) {
	// TODO: Add scope validation here (e.g., require "weighing:read")
	record, err := r.WeighingService.GetWeighingRecord(ctx, id)
	if err != nil {
		return nil, err
	}
	return convertWeighingRecord(record), nil
}

// Helper function to convert ORM model to Domain model
func convertWeighingRecord(r *weighingModels.WeighingRecord) *timbangan.WeighingRecord {
	if r == nil {
		return nil
	}

	// Convert optional strings
	var driverName, vendorName, cargoType *string
	if r.DriverName != "" {
		driverName = &r.DriverName
	}
	if r.VendorName != "" {
		vendorName = &r.VendorName
	}
	if r.CargoType != "" {
		cargoType = &r.CargoType
	}

	// Determine status (basic logic)
	status := timbangan.WeighingStatusPending
	if r.NetWeight > 0 {
		status = timbangan.WeighingStatusCompleted
	} else if r.GrossWeight > 0 || r.TareWeight > 0 {
		status = timbangan.WeighingStatusFirst // Assumption
	}

	return &timbangan.WeighingRecord{
		ID:            r.ID,
		TicketNumber:  r.TicketNumber,
		VehicleNumber: r.VehicleNumber,
		DriverName:    driverName,
		VendorName:    vendorName,
		CargoType:     cargoType,
		GrossWeight:   r.GrossWeight,
		TareWeight:    r.TareWeight,
		NetWeight:     r.NetWeight,
		WeighingTime:  r.WeighingTime,
		CompanyID:     r.CompanyID,
		Status:        status,
		CreatedAt:     r.CreatedAt,
		UpdatedAt:     r.UpdatedAt,
	}
}

// TimbanganHistory is the resolver for the timbanganHistory field.
func (r *queryResolver) TimbanganHistory(ctx context.Context, filter *generated.TimbanganHistoryFilter) (*generated.TimbanganHistoryResponse, error) {
	panic(fmt.Errorf("not implemented: TimbanganHistory - timbanganHistory"))
}

// ValidateDoNumber is the resolver for the validateDoNumber field.
func (r *queryResolver) ValidateDoNumber(ctx context.Context, doNumber string) (*timbangan.DoValidationResult, error) {
	panic(fmt.Errorf("not implemented: ValidateDoNumber - validateDoNumber"))
}

// NewVehicleInQueue is the resolver for the newVehicleInQueue field.
func (r *subscriptionResolver) NewVehicleInQueue(ctx context.Context) (<-chan *timbangan.WeighingQueueItem, error) {
	panic(fmt.Errorf("not implemented: NewVehicleInQueue - newVehicleInQueue"))
}

// WeighingCompleted is the resolver for the weighingCompleted field.
func (r *subscriptionResolver) WeighingCompleted(ctx context.Context) (<-chan *timbangan.WeighingRecord, error) {
	panic(fmt.Errorf("not implemented: WeighingCompleted - weighingCompleted"))
}

// WeighingNumber is the resolver for the weighingNumber field.
func (r *weighingRecordResolver) WeighingNumber(ctx context.Context, obj *timbangan.WeighingRecord) (string, error) {
	panic(fmt.Errorf("not implemented: WeighingNumber - weighingNumber"))
}

// VehiclePlate is the resolver for the vehiclePlate field.
func (r *weighingRecordResolver) VehiclePlate(ctx context.Context, obj *timbangan.WeighingRecord) (string, error) {
	panic(fmt.Errorf("not implemented: VehiclePlate - vehiclePlate"))
}

// SourceEstate is the resolver for the sourceEstate field.
func (r *weighingRecordResolver) SourceEstate(ctx context.Context, obj *timbangan.WeighingRecord) (string, error) {
	panic(fmt.Errorf("not implemented: SourceEstate - sourceEstate"))
}

// SourceDivision is the resolver for the sourceDivision field.
func (r *weighingRecordResolver) SourceDivision(ctx context.Context, obj *timbangan.WeighingRecord) (*string, error) {
	panic(fmt.Errorf("not implemented: SourceDivision - sourceDivision"))
}

// DoNumber is the resolver for the doNumber field.
func (r *weighingRecordResolver) DoNumber(ctx context.Context, obj *timbangan.WeighingRecord) (*string, error) {
	panic(fmt.Errorf("not implemented: DoNumber - doNumber"))
}

// HarvestReferences is the resolver for the harvestReferences field.
func (r *weighingRecordResolver) HarvestReferences(ctx context.Context, obj *timbangan.WeighingRecord) ([]string, error) {
	panic(fmt.Errorf("not implemented: HarvestReferences - harvestReferences"))
}

// FirstWeight is the resolver for the firstWeight field.
func (r *weighingRecordResolver) FirstWeight(ctx context.Context, obj *timbangan.WeighingRecord) (float64, error) {
	panic(fmt.Errorf("not implemented: FirstWeight - firstWeight"))
}

// FirstWeighingTime is the resolver for the firstWeighingTime field.
func (r *weighingRecordResolver) FirstWeighingTime(ctx context.Context, obj *timbangan.WeighingRecord) (*time.Time, error) {
	panic(fmt.Errorf("not implemented: FirstWeighingTime - firstWeighingTime"))
}

// SecondWeight is the resolver for the secondWeight field.
func (r *weighingRecordResolver) SecondWeight(ctx context.Context, obj *timbangan.WeighingRecord) (*float64, error) {
	panic(fmt.Errorf("not implemented: SecondWeight - secondWeight"))
}

// SecondWeighingTime is the resolver for the secondWeighingTime field.
func (r *weighingRecordResolver) SecondWeighingTime(ctx context.Context, obj *timbangan.WeighingRecord) (*time.Time, error) {
	panic(fmt.Errorf("not implemented: SecondWeighingTime - secondWeighingTime"))
}

// TbsCount is the resolver for the tbsCount field.
func (r *weighingRecordResolver) TbsCount(ctx context.Context, obj *timbangan.WeighingRecord) (*int32, error) {
	panic(fmt.Errorf("not implemented: TbsCount - tbsCount"))
}

// BrondolanWeight is the resolver for the brondolanWeight field.
func (r *weighingRecordResolver) BrondolanWeight(ctx context.Context, obj *timbangan.WeighingRecord) (*float64, error) {
	panic(fmt.Errorf("not implemented: BrondolanWeight - brondolanWeight"))
}

// Bjr is the resolver for the bjr field.
func (r *weighingRecordResolver) Bjr(ctx context.Context, obj *timbangan.WeighingRecord) (*float64, error) {
	panic(fmt.Errorf("not implemented: Bjr - bjr"))
}

// QualityGrade is the resolver for the qualityGrade field.
func (r *weighingRecordResolver) QualityGrade(ctx context.Context, obj *timbangan.WeighingRecord) (*string, error) {
	panic(fmt.Errorf("not implemented: QualityGrade - qualityGrade"))
}

// GradingNotes is the resolver for the gradingNotes field.
func (r *weighingRecordResolver) GradingNotes(ctx context.Context, obj *timbangan.WeighingRecord) (*string, error) {
	panic(fmt.Errorf("not implemented: GradingNotes - gradingNotes"))
}

// Status is the resolver for the status field.
func (r *weighingRecordResolver) Status(ctx context.Context, obj *timbangan.WeighingRecord) (timbangan.WeighingStatus, error) {
	panic(fmt.Errorf("not implemented: Status - status"))
}

// OperatorID is the resolver for the operatorId field.
func (r *weighingRecordResolver) OperatorID(ctx context.Context, obj *timbangan.WeighingRecord) (string, error) {
	panic(fmt.Errorf("not implemented: OperatorID - operatorId"))
}

// OperatorName is the resolver for the operatorName field.
func (r *weighingRecordResolver) OperatorName(ctx context.Context, obj *timbangan.WeighingRecord) (string, error) {
	panic(fmt.Errorf("not implemented: OperatorName - operatorName"))
}

// Photos is the resolver for the photos field.
func (r *weighingRecordResolver) Photos(ctx context.Context, obj *timbangan.WeighingRecord) ([]string, error) {
	panic(fmt.Errorf("not implemented: Photos - photos"))
}

// Notes is the resolver for the notes field.
func (r *weighingRecordResolver) Notes(ctx context.Context, obj *timbangan.WeighingRecord) (*string, error) {
	panic(fmt.Errorf("not implemented: Notes - notes"))
}

// WeighingRecord returns generated.WeighingRecordResolver implementation.
func (r *Resolver) WeighingRecord() generated.WeighingRecordResolver {
	return &weighingRecordResolver{r}
}

type weighingRecordResolver struct{ *Resolver }
