// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'harvest_entity.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Harvest _$HarvestFromJson(Map<String, dynamic> json) => Harvest(
      id: json['id'] as String,
      employeeId: json['employeeId'] as String,
      employeeName: json['employeeName'] as String,
      employeeNik: json['employeeNik'] as String?,
      employeeDivisionId: json['employeeDivisionId'] as String?,
      employeeDivisionName: json['employeeDivisionName'] as String?,
      blockId: json['blockId'] as String,
      blockName: json['blockName'] as String,
      blockCode: json['blockCode'] as String?,
      divisionId: json['divisionId'] as String,
      divisionName: json['divisionName'] as String,
      divisionCode: json['divisionCode'] as String?,
      estateId: json['estateId'] as String,
      estateName: json['estateName'] as String,
      tbsQuantity: (json['tbsQuantity'] as num).toDouble(),
      jumlahJanjang: (json['jumlahJanjang'] as num?)?.toInt() ?? 0,
      jjgMatang: (json['jjgMatang'] as num?)?.toInt() ?? 0,
      jjgMentah: (json['jjgMentah'] as num?)?.toInt() ?? 0,
      jjgLewatMatang: (json['jjgLewatMatang'] as num?)?.toInt() ?? 0,
      jjgBusukAbnormal: (json['jjgBusukAbnormal'] as num?)?.toInt() ?? 0,
      jjgTangkaiPanjang: (json['jjgTangkaiPanjang'] as num?)?.toInt() ?? 0,
      tbsQuality: (json['tbsQuality'] as num).toDouble(),
      qualityGrade: json['qualityGrade'] as String,
      harvestDate: DateTime.parse(json['harvestDate'] as String),
      createdAt: DateTime.parse(json['createdAt'] as String),
      updatedAt: json['updatedAt'] == null
          ? null
          : DateTime.parse(json['updatedAt'] as String),
      status: json['status'] as String,
      approvedBy: json['approvedBy'] as String?,
      approvedAt: json['approvedAt'] as String?,
      rejectionReason: json['rejectionReason'] as String?,
      notes: json['notes'] as String?,
      latitude: (json['latitude'] as num?)?.toDouble(),
      longitude: (json['longitude'] as num?)?.toDouble(),
      imageUrl: json['imageUrl'] as String?,
      mandorId: json['mandorId'] as String,
      mandorName: json['mandorName'] as String,
      isSynced: json['isSynced'] as bool? ?? false,
      syncErrorMessage: json['syncErrorMessage'] as String?,
      companyId: json['companyId'] as String?,
      managerId: json['managerId'] as String?,
      asistenId: json['asistenId'] as String?,
      mandorScope: json['mandorScope'] as String?,
    );

Map<String, dynamic> _$HarvestToJson(Harvest instance) => <String, dynamic>{
      'id': instance.id,
      'employeeId': instance.employeeId,
      'employeeName': instance.employeeName,
      'employeeNik': instance.employeeNik,
      'employeeDivisionId': instance.employeeDivisionId,
      'employeeDivisionName': instance.employeeDivisionName,
      'blockId': instance.blockId,
      'blockName': instance.blockName,
      'blockCode': instance.blockCode,
      'divisionId': instance.divisionId,
      'divisionName': instance.divisionName,
      'divisionCode': instance.divisionCode,
      'estateId': instance.estateId,
      'estateName': instance.estateName,
      'tbsQuantity': instance.tbsQuantity,
      'jumlahJanjang': instance.jumlahJanjang,
      'jjgMatang': instance.jjgMatang,
      'jjgMentah': instance.jjgMentah,
      'jjgLewatMatang': instance.jjgLewatMatang,
      'jjgBusukAbnormal': instance.jjgBusukAbnormal,
      'jjgTangkaiPanjang': instance.jjgTangkaiPanjang,
      'tbsQuality': instance.tbsQuality,
      'qualityGrade': instance.qualityGrade,
      'harvestDate': instance.harvestDate.toIso8601String(),
      'createdAt': instance.createdAt.toIso8601String(),
      'updatedAt': instance.updatedAt?.toIso8601String(),
      'status': instance.status,
      'approvedBy': instance.approvedBy,
      'approvedAt': instance.approvedAt,
      'rejectionReason': instance.rejectionReason,
      'notes': instance.notes,
      'latitude': instance.latitude,
      'longitude': instance.longitude,
      'imageUrl': instance.imageUrl,
      'mandorId': instance.mandorId,
      'mandorName': instance.mandorName,
      'isSynced': instance.isSynced,
      'syncErrorMessage': instance.syncErrorMessage,
      'companyId': instance.companyId,
      'managerId': instance.managerId,
      'asistenId': instance.asistenId,
      'mandorScope': instance.mandorScope,
    };

Employee _$EmployeeFromJson(Map<String, dynamic> json) => Employee(
      id: json['id'] as String,
      name: json['name'] as String,
      code: json['code'] as String,
      divisionId: json['divisionId'] as String,
      divisionName: json['divisionName'] as String,
      role: json['role'] as String,
      isActive: json['isActive'] as bool? ?? true,
      createdAt: DateTime.parse(json['createdAt'] as String),
    );

Map<String, dynamic> _$EmployeeToJson(Employee instance) => <String, dynamic>{
      'id': instance.id,
      'name': instance.name,
      'code': instance.code,
      'divisionId': instance.divisionId,
      'divisionName': instance.divisionName,
      'role': instance.role,
      'isActive': instance.isActive,
      'createdAt': instance.createdAt.toIso8601String(),
    };

Block _$BlockFromJson(Map<String, dynamic> json) => Block(
      id: json['id'] as String,
      name: json['name'] as String,
      code: json['code'] as String,
      divisionId: json['divisionId'] as String,
      divisionName: json['divisionName'] as String,
      divisionCode: json['divisionCode'] as String?,
      estateId: json['estateId'] as String,
      estateName: json['estateName'] as String,
      area: (json['area'] as num).toDouble(),
      plantYear: (json['plantYear'] as num).toInt(),
      varietyType: json['varietyType'] as String,
      isActive: json['isActive'] as bool? ?? true,
    );

Map<String, dynamic> _$BlockToJson(Block instance) => <String, dynamic>{
      'id': instance.id,
      'name': instance.name,
      'code': instance.code,
      'divisionId': instance.divisionId,
      'divisionName': instance.divisionName,
      'divisionCode': instance.divisionCode,
      'estateId': instance.estateId,
      'estateName': instance.estateName,
      'area': instance.area,
      'plantYear': instance.plantYear,
      'varietyType': instance.varietyType,
      'isActive': instance.isActive,
    };
