// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"agrinovagraphql/server/internal/auth/internal/config"

	mobileApp "agrinovagraphql/server/internal/auth/features/mobile/application"
	mobileInfra "agrinovagraphql/server/internal/auth/features/mobile/infrastructure"
	mobileGraphQL "agrinovagraphql/server/internal/auth/features/mobile/interfaces/graphql"
	sharedApp "agrinovagraphql/server/internal/auth/features/shared/application"
	sharedInfra "agrinovagraphql/server/internal/auth/features/shared/infrastructure/postgres"
	securityInfra "agrinovagraphql/server/internal/auth/features/shared/infrastructure/security"
	webApp "agrinovagraphql/server/internal/auth/features/web/application"
	webInfra "agrinovagraphql/server/internal/auth/features/web/infrastructure"
	webGraphQL "agrinovagraphql/server/internal/auth/features/web/interfaces/graphql"

	"time"

	"gorm.io/gorm"
)

// Injectors from wire.go:

func NewAuthModuleV2(db *gorm.DB) (*AuthModule, error) {
	// Load configuration
	cfg, err := config.Load()
	if err != nil {
		return nil, err
	}

	// Shared repositories
	userRepo := sharedInfra.NewUserRepository(db)
	sessionRepo := sharedInfra.NewSessionRepository(db)
	deviceRepo := sharedInfra.NewDeviceRepository(db)
	assignmentRepo := sharedInfra.NewAssignmentRepository(db)
	companyRepo := sharedInfra.NewCompanyRepository(db)

	// Security services
	passwordService := securityInfra.NewPasswordService()
	securityLogger := securityInfra.NewSecurityLogger(true)

	// Web configuration and services
	webConfig := webApp.WebConfig{
		SessionDuration:    cfg.Web.SessionDuration,
		RememberMeDuration: cfg.Web.RememberMeDuration,
		CSRFSecret:         []byte(cfg.Web.CSRFSecret),
	}

	webCookieConfig := webInfra.CookieConfig{
		SessionCookieName: cfg.Web.Cookie.SessionName,
		CSRFCookieName:    cfg.Web.Cookie.CSRFName,
		Domain:            cfg.Web.Cookie.Domain,
		SecureCookies:     cfg.Web.Cookie.Secure,
		SameSitePolicy:    cfg.Web.Cookie.SameSite,
		SessionDuration:   cfg.Web.SessionDuration,
		CSRFTokenDuration: cfg.Web.Cookie.CSRFDuration,
		CSRFSecret:        []byte(cfg.Web.CSRFSecret),
	}

	cookieService := webInfra.NewCookieService(webCookieConfig)
	rateLimiter := securityInfra.NewRateLimiter(5, time.Minute, 5*time.Minute)
	webAuthService := webApp.NewService(
		sessionRepo,
		userRepo,
		assignmentRepo,
		companyRepo,
		cookieService,
		passwordService,
		securityLogger,
		rateLimiter,
		webConfig,
	)

	webResolver := webGraphQL.NewResolver(webAuthService)

	// Mobile configuration and services
	mobileConfig := mobileApp.MobileConfig{
		AccessTokenDuration:  cfg.Mobile.AccessTokenDuration,
		RefreshTokenDuration: cfg.Mobile.RefreshTokenDuration,
		OfflineTokenDuration: cfg.Mobile.OfflineTokenDuration,
		MaxDevicesPerUser:    cfg.Mobile.MaxDevicesPerUser,
		DeviceSecret:         cfg.Mobile.DeviceSecret,
	}

	mobileJWTConfig := mobileInfra.JWTConfig{
		AccessTokenSecret:    cfg.Mobile.JWT.AccessSecret,
		RefreshTokenSecret:   cfg.Mobile.JWT.RefreshSecret,
		OfflineTokenSecret:   cfg.Mobile.JWT.OfflineSecret,
		AccessTokenDuration:  cfg.Mobile.AccessTokenDuration,
		RefreshTokenDuration: cfg.Mobile.RefreshTokenDuration,
		OfflineTokenDuration: cfg.Mobile.OfflineTokenDuration,
		Issuer:               cfg.Mobile.JWT.Issuer,
	}

	jwtService := mobileInfra.NewJWTService(db, mobileJWTConfig)
	mobileAuthService := mobileApp.NewService(
		userRepo,
		deviceRepo,
		assignmentRepo,
		jwtService,
		passwordService,
		securityLogger,
		mobileConfig,
	)

	mobileResolver := mobileGraphQL.NewResolver(mobileAuthService)

	// Shared Auth Service
	sharedAuthService := sharedApp.NewSharedAuthService(
		userRepo,
		passwordService,
		deviceRepo,
		sessionRepo,
		jwtService,
		securityLogger,
	)

	// User Management Service
	userManagementService := webApp.NewUserManagementService(
		userRepo,
		passwordService,
		securityLogger,
	)

	// Create module
	authModule := &AuthModule{
		WebResolver:           webResolver,
		MobileResolver:        mobileResolver,
		SharedAuthService:     sharedAuthService,
		UserManagementService: userManagementService,
		WebAppService:         webAuthService,
		CookieService:         cookieService,
		TokenService:          jwtService,
	}

	return authModule, nil
}
